<?php
require_once dirname(__DIR__) . '/config/config.php';
require_once dirname(__DIR__) . '/config/database.php';
require_once dirname(__DIR__) . '/config/functions.php';
require_once dirname(__DIR__) . '/config/session.php';
require_once dirname(__DIR__) . '/modules/projects/project_lib.php';
Session::start();
$role=akp_role();$uid=akp_user_id();
if(!Session::isLoggedIn()||!in_array($role,['projects_manager','project_supervisor'],true)){header('Location: '.APP_URL.'index.php');exit();}
$pageTitle=t('projects.dashboard_title');$active='projects_dashboard';
if($role==='projects_manager'){
$stats=dbFetchOne("SELECT COUNT(*) total_projects,SUM(CASE WHEN BINARY current_status IN (BINARY 'active', BINARY 'reopened') THEN 1 ELSE 0 END) active_projects,SUM(CASE WHEN approval_status='submitted' THEN 1 ELSE 0 END) pending_approval,COALESCE(SUM(CASE WHEN BINARY current_status IN (BINARY 'active', BINARY 'reopened') THEN COALESCE((SELECT SUM(COALESCE(bl.approved_amount, bl.estimated_amount)) FROM project_budgets b JOIN project_budget_lines bl ON bl.budget_id=b.id WHERE b.project_id=x.id AND b.status='approved'), target_amount) ELSE 0 END),0) active_budget FROM (SELECT p.id,p.target_amount,COALESCE(l.lifecycle_status,p.status) current_status,COALESCE((SELECT pa.approval_status FROM project_approval pa WHERE pa.project_id=p.id),'approved') approval_status FROM other_projects p LEFT JOIN project_lifecycle l ON l.project_id=p.id) x");
$pendingApprovals=dbFetchAll("SELECT p.id,p.name,p.project_code,pa.submitted_at,u.full_name submitted_by_name FROM project_approval pa JOIN other_projects p ON p.id=pa.project_id LEFT JOIN users u ON u.id=pa.submitted_by WHERE pa.approval_status='submitted' ORDER BY pa.submitted_at DESC LIMIT 5");
$recentProjects=dbFetchAll("SELECT p.id,p.name,p.project_code,COALESCE(l.lifecycle_status,p.status) status,p.target_amount FROM other_projects p LEFT JOIN project_lifecycle l ON l.project_id=p.id ORDER BY p.id DESC LIMIT 5");
}else{
$stats=dbFetchOne("SELECT COUNT(DISTINCT p.id) assigned_projects,SUM(CASE WHEN BINARY COALESCE(l.lifecycle_status,p.status) IN (BINARY 'active', BINARY 'reopened') THEN 1 ELSE 0 END) active_assigned,COUNT(DISTINCT lh.id) pending_labor,COUNT(DISTINCT pm.id) upcoming_milestones FROM other_projects p LEFT JOIN project_lifecycle l ON l.project_id=p.id LEFT JOIN project_supervisor_assignments psa ON psa.project_id=p.id AND psa.ended_at IS NULL AND psa.supervisor_user_id=? LEFT JOIN project_labor_helpers lh ON lh.project_id=p.id AND lh.supervisor_user_id=? AND lh.status IN ('planned','in_progress') LEFT JOIN project_milestones pm ON pm.project_id=p.id AND pm.status='pending' WHERE psa.supervisor_user_id=?",[$uid,$uid,$uid]);
$assignedProjects=dbFetchAll("SELECT p.id,p.name,p.project_code,COALESCE(l.lifecycle_status,p.status) status FROM other_projects p JOIN project_supervisor_assignments psa ON psa.project_id=p.id AND psa.ended_at IS NULL LEFT JOIN project_lifecycle l ON l.project_id=p.id WHERE psa.supervisor_user_id=? ORDER BY p.id DESC LIMIT 5",[$uid]);
$pendingLabor=dbFetchAll("SELECT lh.id,lh.provider_name,lh.work_description,p.name project_name,lh.status FROM project_labor_helpers lh JOIN other_projects p ON p.id=lh.project_id WHERE lh.supervisor_user_id=? AND lh.status IN ('planned','in_progress') ORDER BY lh.id DESC LIMIT 5",[$uid]);
}
include dirname(__DIR__).'/includes/header.php';
?>
<div class="welcome-section fade-in"><h2><?php echo e(t('dashboard.welcome_user',['name'=>$role==='projects_manager'?t('projects.manager'):t('projects.supervisor')])); ?></h2><p><?php echo e(t($role==='projects_manager'?'projects.manager_intro':'projects.supervisor_intro')); ?></p><div class="quick-actions mt-3"><?php if($role==='projects_manager'): ?><a href="<?php echo APP_URL; ?>modules/projects/form.php" class="btn btn-primary btn-sm me-2"><i class="fas fa-plus me-1"></i><?php echo e(t('projects.new')); ?></a><a href="<?php echo APP_URL; ?>modules/projects/index.php" class="btn btn-outline-secondary btn-sm"><i class="fas fa-list me-1"></i><?php echo e(t('projects.portfolio')); ?></a><?php else: ?><a href="<?php echo APP_URL; ?>modules/projects/index.php" class="btn btn-primary btn-sm me-2"><i class="fas fa-folder-open me-1"></i><?php echo e(t('navigation.my_projects')); ?></a><?php endif; ?></div></div>
<?php include dirname(__DIR__).'/includes/alerts.php'; ?>
<div class="row g-3 mb-4"><?php if($role==='projects_manager'): ?><?php $cards=[[(int)($stats['total_projects']??0),'projects.total','fa-diagram-project','primary'],[(int)($stats['active_projects']??0),'projects.active','fa-spinner','success'],[(int)($stats['pending_approval']??0),'projects.pending_approval','fa-clock','warning'],[(float)($stats['active_budget']??0),'projects.active_budget','fa-coins','info']]; ?><?php else: ?><?php $cards=[[(int)($stats['assigned_projects']??0),'projects.assigned','fa-folder-open','primary'],[(int)($stats['active_assigned']??0),'projects.active_assigned','fa-play-circle','success'],[(int)($stats['pending_labor']??0),'projects.pending_labor','fa-hard-hat','warning'],[(int)($stats['upcoming_milestones']??0),'projects.upcoming_milestones','fa-flag-checkered','info']]; ?><?php endif; ?><?php foreach($cards as $c): ?><div class="col-md-3"><div class="card fade-in border-<?php echo $c[3]; ?> h-100"><div class="card-body text-center"><i class="fas <?php echo $c[2]; ?> fa-2x text-<?php echo $c[3]; ?> mb-2"></i><h3><?php echo is_float($c[0])?number_format($c[0],0):$c[0]; ?></h3><p class="text-muted mb-0"><?php echo e(t($c[1])); ?></p></div></div></div><?php endforeach; ?></div>
<div class="row g-3"><div class="col-lg-8">
<?php if($role==='projects_manager'): ?><div class="card fade-in mb-3"><div class="card-header d-flex justify-content-between align-items-center"><h5 class="mb-0"><i class="fas fa-clipboard-check me-2"></i><?php echo e(t('projects.pending_approvals')); ?></h5><a href="<?php echo APP_URL; ?>modules/projects/index.php" class="btn btn-sm btn-outline-primary"><?php echo e(t('common.view_all')); ?></a></div><div class="card-body p-0"><?php if(empty($pendingApprovals)): ?><p class="text-muted text-center py-4 mb-0"><?php echo e(t('projects.no_pending_approvals')); ?></p><?php else: ?><div class="table-responsive"><table class="table table-hover mb-0 align-middle"><thead><tr><th><?php echo e(t('projects.project')); ?></th><th><?php echo e(t('projects.submitted_by')); ?></th><th><?php echo e(t('projects.submitted_at')); ?></th><th><?php echo e(t('common.actions')); ?></th></tr></thead><tbody><?php foreach($pendingApprovals as $pa): ?><tr><td><strong><?php echo e($pa['name']); ?></strong><br><small class="text-muted"><?php echo e($pa['project_code']); ?></small></td><td><?php echo e($pa['submitted_by_name']??t('common.unknown')); ?></td><td><?php echo e($pa['submitted_at']); ?></td><td><a href="<?php echo APP_URL; ?>modules/projects/view.php?id=<?php echo (int)$pa['id']; ?>" class="btn btn-sm btn-primary"><i class="fas fa-eye"></i> <?php echo e(t('projects.review')); ?></a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div>
<div class="card fade-in"><div class="card-header"><h5 class="mb-0"><i class="fas fa-history me-2"></i><?php echo e(t('projects.recent')); ?></h5></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0 align-middle"><thead><tr><th><?php echo e(t('projects.code')); ?></th><th><?php echo e(t('projects.project')); ?></th><th><?php echo e(t('projects.budget')); ?></th><th><?php echo e(t('common.status')); ?></th><th></th></tr></thead><tbody><?php foreach($recentProjects as $rp): $key=['planned'=>'projects.planned','active'=>'projects.active','completed'=>'projects.completed','under_review'=>'projects.under_review','closed'=>'projects.closed','reopened'=>'projects.reopened','cancelled'=>'projects.cancelled'][$rp['status']]??'common.status'; ?><tr><td><code><?php echo e($rp['project_code']); ?></code></td><td><strong><?php echo e($rp['name']); ?></strong></td><td><?php echo number_format((float)$rp['target_amount'],0); ?> <?php echo e(t('hr.currency_sdg')); ?></td><td><span class="badge bg-secondary"><?php echo e(t($key)); ?></span></td><td><a href="<?php echo APP_URL; ?>modules/projects/view.php?id=<?php echo (int)$rp['id']; ?>" class="btn btn-sm btn-outline-primary"><i class="fas fa-eye"></i></a></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php else: ?><div class="card fade-in mb-3"><div class="card-header"><h5 class="mb-0"><i class="fas fa-briefcase me-2"></i><?php echo e(t('projects.assigned_projects')); ?></h5></div><div class="card-body p-0"><?php if(empty($assignedProjects)): ?><p class="text-muted text-center py-4 mb-0"><?php echo e(t('projects.no_assigned')); ?></p><?php else: ?><div class="table-responsive"><table class="table table-hover mb-0 align-middle"><thead><tr><th><?php echo e(t('projects.code')); ?></th><th><?php echo e(t('projects.project')); ?></th><th><?php echo e(t('common.status')); ?></th><th></th></tr></thead><tbody><?php foreach($assignedProjects as $ap): $key=['planned'=>'projects.planned','active'=>'projects.active','completed'=>'projects.completed','under_review'=>'projects.under_review','closed'=>'projects.closed','reopened'=>'projects.reopened','cancelled'=>'projects.cancelled'][$ap['status']]??'common.status'; ?><tr><td><code><?php echo e($ap['project_code']); ?></code></td><td><strong><?php echo e($ap['name']); ?></strong></td><td><span class="badge bg-secondary"><?php echo e(t($key)); ?></span></td><td><a href="<?php echo APP_URL; ?>modules/projects/view.php?id=<?php echo (int)$ap['id']; ?>" class="btn btn-sm btn-primary"><i class="fas fa-eye"></i> <?php echo e(t('common.view')); ?></a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div><div class="card fade-in"><div class="card-header"><h5 class="mb-0"><i class="fas fa-hard-hat me-2"></i><?php echo e(t('projects.active_labor')); ?></h5></div><div class="card-body p-0"><?php if(empty($pendingLabor)): ?><p class="text-muted text-center py-4 mb-0"><?php echo e(t('projects.no_active_labor')); ?></p><?php else: ?><div class="table-responsive"><table class="table table-hover mb-0 align-middle"><thead><tr><th><?php echo e(t('projects.project')); ?></th><th><?php echo e(t('projects.provider')); ?></th><th><?php echo e(t('projects.work_description')); ?></th><th><?php echo e(t('common.status')); ?></th></tr></thead><tbody><?php foreach($pendingLabor as $pl): ?><tr><td><?php echo e($pl['project_name']); ?></td><td><strong><?php echo e($pl['provider_name']); ?></strong></td><td><?php echo e($pl['work_description']); ?></td><td><span class="badge bg-secondary"><?php echo e(t($pl['status']==='in_progress'?'projects.in_progress':'projects.planned')); ?></span></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div><?php endif; ?>
</div><div class="col-lg-4"><div class="card fade-in mb-3"><div class="card-header"><h5 class="mb-0"><i class="fas fa-bolt me-2"></i><?php echo e(t('projects.quick_actions')); ?></h5></div><div class="card-body"><div class="d-grid gap-2"><?php if($role==='projects_manager'): ?><a href="<?php echo APP_URL; ?>modules/projects/form.php" class="btn btn-outline-primary"><i class="fas fa-plus me-2"></i><?php echo e(t('projects.create_new')); ?></a><a href="<?php echo APP_URL; ?>modules/projects/index.php" class="btn btn-outline-secondary"><i class="fas fa-chart-pie me-2"></i><?php echo e(t('projects.portfolio_report')); ?></a><?php else: ?><a href="<?php echo APP_URL; ?>modules/projects/index.php" class="btn btn-outline-primary"><i class="fas fa-list me-2"></i><?php echo e(t('projects.view_my_projects')); ?></a><div class="alert alert-info small mb-0 mt-2"><i class="fas fa-info-circle me-1"></i><?php echo e(t('projects.supervisor_hint')); ?></div><?php endif; ?></div></div></div><div class="card fade-in"><div class="card-header"><h5 class="mb-0"><i class="fas fa-<?php echo $role==='projects_manager'?'bell':'lightbulb'; ?> me-2"></i><?php echo e(t($role==='projects_manager'?'projects.system_alerts':'projects.supervisor_tips')); ?></h5></div><div class="card-body"><ul class="list-unstyled mb-0 small"><?php if($role==='projects_manager'): ?><li class="mb-3"><strong><?php echo e(t('projects.budget_review')); ?></strong><p class="text-muted mb-0"><?php echo e(t('projects.budget_review_text')); ?></p></li><li><strong><?php echo e(t('projects.pending_expenses')); ?></strong><p class="text-muted mb-0"><?php echo e(t('projects.pending_expenses_text')); ?></p></li><?php else: ?><li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i><?php echo e(t('projects.tip_labor')); ?></li><li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i><?php echo e(t('projects.tip_progress')); ?></li><li><i class="fas fa-check-circle text-success me-2"></i><?php echo e(t('projects.tip_documents')); ?></li><?php endif; ?></ul></div></div></div></div>
<?php include dirname(__DIR__).'/includes/footer.php'; ?>