<?php
require_once dirname(__DIR__,2).'/config/config.php';require_once dirname(__DIR__,2).'/config/database.php';require_once dirname(__DIR__,2).'/config/functions.php';require_once dirname(__DIR__,2).'/config/session.php';Session::start();
if(!Session::isLoggedIn()||Session::getUserRole()!=='admin'){header('Location: '.APP_URL.'index.php');exit();}
$pageTitle=t('system.health_title');$active='system';$checks=[];$checks[]=[t('system.php_version'),version_compare(PHP_VERSION,'8.1.0','>='),PHP_VERSION];
foreach(['pdo_mysql','mbstring','zip','json','simplexml'] as $ext)$checks[]=[t('system.php_extension',['extension'=>$ext]),extension_loaded($ext),extension_loaded($ext)?t('system.loaded'):t('system.missing')];
try{dbFetchOne('SELECT 1');$checks[]=[t('system.database'),true,t('system.connected')];}catch(Throwable $e){$checks[]=[t('system.database'),false,$e->getMessage()];}
$tables=['users','roles','letters','supervisor_letters','sponsors','families','family_children','sponsorships','sponsorship_children','transactions','settings','audit_log'];foreach($tables as $table){try{$c=(int)(dbFetchOne("SELECT COUNT(*) c FROM `$table`")['c']??0);$checks[]=[t('system.table',['table'=>$table]),true,t('system.records',['count'=>$c])];}catch(Throwable $e){$checks[]=[t('system.table',['table'=>$table]),false,t('system.table_error')];}}
$root=dirname(__DIR__,2);foreach(['storage/backups','storage/logs','storage/imports'] as $d){$p=$root.'/'.$d;$checks[]=[t('system.writable_folder',['folder'=>$d]),is_dir($p)&&is_writable($p),is_dir($p)?t('system.exists'):t('system.missing')];}
$checks[]=[t('system.port_check'),str_contains(APP_URL,':8081'),APP_URL];$checks[]=[t('system.session'),class_exists('Session',false)&&Session::isLoggedIn(),Session::getUserRole()];$bk=glob($root.'/storage/backups/*.sql')?:[];$checks[]=[t('system.backup'),count($bk)>0,$bk?date('Y-m-d H:i',max(array_map('filemtime',$bk))):t('system.no_backup')];$checks[]=[t('system.disk_space'),true,number_format(disk_free_space($root)/1073741824,2).' GB'];
include dirname(__DIR__,2).'/includes/header.php';?>
<div class="welcome-section fade-in"><h2><?php echo e(t('system.health_title')); ?></h2><p><?php echo e(t('system.health_intro')); ?></p></div>
<div class="card fade-in"><div class="card-body"><table class="table align-middle"><thead><tr><th><?php echo e(t('system.check')); ?></th><th><?php echo e(t('system.result')); ?></th><th><?php echo e(t('system.details')); ?></th></tr></thead><tbody><?php foreach($checks as $c): ?><tr><td><?php echo e($c[0]); ?></td><td><?php echo $c[1]?'<span class="badge bg-success">'.e(t('system.healthy')).'</span>':'<span class="badge bg-danger">'.e(t('system.problem')).'</span>'; ?></td><td><small><?php echo e($c[2]); ?></small></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php include dirname(__DIR__,2).'/includes/footer.php'; ?>