-- Ahl El Kheir - Family Code Integrity Migration
--
-- Purpose:
--   1. Repair legacy families whose family_code is NULL/empty.
--   2. Standardize the legacy FAM-xxxxxx format to IMP-FAM-xxxxxx.
--   3. Prevent future families from being stored without a valid family code.
--   4. Keep family_code unique.
--
-- The current family-code convention is derived from the family primary key:
--   id 246 -> IMP-FAM-000246
--
-- Run this script once against the AhlElKheir database.

START TRANSACTION;

/* -------------------------------------------------------------
   1. Repair missing legacy family codes.
   ------------------------------------------------------------- */
UPDATE families
SET family_code = CONCAT('IMP-FAM-', LPAD(id, 6, '0'))
WHERE family_code IS NULL OR TRIM(family_code) = '';

/* -------------------------------------------------------------
   2. Normalize codes generated by the old application format.
      Old: FAM-000247
      New: IMP-FAM-000247
   ------------------------------------------------------------- */
UPDATE families
SET family_code = CONCAT('IMP-FAM-', SUBSTRING(TRIM(family_code), 5))
WHERE TRIM(family_code) REGEXP '^FAM-[0-9]{6}$';

/* -------------------------------------------------------------
   3. Safety check: the next statement must return zero rows.
      If it returns rows, stop and resolve the duplicates before
      creating the unique index below.
   ------------------------------------------------------------- */
SELECT family_code, COUNT(*) AS duplicate_count
FROM families
WHERE family_code IS NOT NULL AND TRIM(family_code) <> ''
GROUP BY family_code
HAVING COUNT(*) > 1;

/* -------------------------------------------------------------
   4. family_code must never be NULL/empty from this point forward.
   ------------------------------------------------------------- */
ALTER TABLE families
    MODIFY COLUMN family_code VARCHAR(50) NOT NULL;

/* -------------------------------------------------------------
   5. Add a unique constraint if one does not already exist.
   ------------------------------------------------------------- */
SET @family_code_unique_exists := (
    SELECT COUNT(*)
    FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = 'families'
      AND column_name = 'family_code'
      AND non_unique = 0
);

SET @add_family_code_unique_sql := IF(
    @family_code_unique_exists = 0,
    'ALTER TABLE families ADD UNIQUE KEY uq_families_family_code (family_code)',
    'SELECT 1'
);

PREPARE stmt_family_code_unique FROM @add_family_code_unique_sql;
EXECUTE stmt_family_code_unique;
DEALLOCATE PREPARE stmt_family_code_unique;

/* -------------------------------------------------------------
   6. Database-level guard for INSERT.
      The application historically generated FAM-xxxxxx. Convert
      that legacy format automatically, while rejecting missing or
      malformed codes from imports/manual SQL.
   ------------------------------------------------------------- */
DROP TRIGGER IF EXISTS trg_families_family_code_bi;

DELIMITER $$
CREATE TRIGGER trg_families_family_code_bi
BEFORE INSERT ON families
FOR EACH ROW
BEGIN
    SET NEW.family_code = NULLIF(TRIM(NEW.family_code), '');

    IF NEW.family_code IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'family_code is required for every family';
    END IF;

    IF NEW.family_code REGEXP '^FAM-[0-9]{6}$' THEN
        SET NEW.family_code = CONCAT('IMP-FAM-', SUBSTRING(NEW.family_code, 5));
    END IF;

    IF NEW.family_code NOT REGEXP '^IMP-FAM-[0-9]{6}$' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Invalid family_code. Expected IMP-FAM-######';
    END IF;
END$$
DELIMITER ;

/* -------------------------------------------------------------
   7. Database-level guard for UPDATE.
      This prevents an existing family code from being erased or
      changed to an invalid format.
   ------------------------------------------------------------- */
DROP TRIGGER IF EXISTS trg_families_family_code_bu;

DELIMITER $$
CREATE TRIGGER trg_families_family_code_bu
BEFORE UPDATE ON families
FOR EACH ROW
BEGIN
    SET NEW.family_code = NULLIF(TRIM(NEW.family_code), '');

    IF NEW.family_code IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'family_code cannot be empty';
    END IF;

    IF NEW.family_code REGEXP '^FAM-[0-9]{6}$' THEN
        SET NEW.family_code = CONCAT('IMP-FAM-', SUBSTRING(NEW.family_code, 5));
    END IF;

    IF NEW.family_code NOT REGEXP '^IMP-FAM-[0-9]{6}$' THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Invalid family_code. Expected IMP-FAM-######';
    END IF;
END$$
DELIMITER ;

COMMIT;

/* -------------------------------------------------------------
   Verification
   ------------------------------------------------------------- */
SELECT
    COUNT(*) AS total_families,
    SUM(CASE WHEN family_code IS NULL OR TRIM(family_code) = '' THEN 1 ELSE 0 END) AS missing_codes,
    SUM(CASE WHEN family_code REGEXP '^IMP-FAM-[0-9]{6}$' THEN 1 ELSE 0 END) AS valid_codes
FROM families;
