<?php
// modules/families/index.php - Families list (scoped + prefix search + edit) — Orphan-level pivot
require_once dirname(__DIR__, 2) . '/config/config.php';
require_once dirname(__DIR__, 2) . '/config/database.php';
require_once dirname(__DIR__, 2) . '/config/functions.php';
require_once dirname(__DIR__, 2) . '/config/session.php';
Session::start();
if (!Session::isLoggedIn()) { header('Location: ' . APP_URL . 'index.php'); exit(); }
$role = Session::getUserRole();
$currentUserId = Session::getUserId();
if ($currentUserId > 0) {
    $dbRole = dbFetchOne("SELECT r.code AS role_code FROM users u JOIN roles r ON r.id = u.role_id WHERE u.id = ? LIMIT 1", [$currentUserId]);
    if ($dbRole && !empty($dbRole['role_code'])) { $role = (string)$dbRole['role_code']; $_SESSION['user_role'] = $role; }
}
if (!in_array($role, ['admin', 'vice_general_manager', 'general_manager', 'supervisor', 'nanny'], true)) { header('Location: ' . APP_URL . 'index.php'); exit(); }
$pageTitle = t('families.title'); $active = 'families';
$norm = function (string $s): string { $s = preg_replace('/[\x{064B}-\x{0652}\x{0640}\x{200B}-\x{200D}\x{FEFF}]/u', '', $s); $s = str_replace(['أ','إ','آ','ٱ'], 'ا', $s); $s = str_replace(['ة'], 'ه', $s); return mb_strtolower(preg_replace('/\s+/u', ' ', trim($s)), 'UTF-8'); };
$q = trim($_GET['q'] ?? ''); $fStatus = trim($_GET['status'] ?? ''); $page = max(1, (int)($_GET['page'] ?? 1)); $perPage = 50; $nq = $norm($q);
$myIds = null; $uid = Session::getUserId();
if ($role === 'supervisor') {
    $myLetterIds = array_map('intval', array_column(dbFetchAll("SELECT letter_id FROM supervisor_letters WHERE supervisor_id = ?", [$uid]), 'letter_id'));
    $letters = dbFetchAll("SELECT id, code FROM letters"); $myIds = [];
    foreach (dbFetchAll("SELECT id, supervisor_id, legacy_mother_first_letter FROM families") as $f) {
        if ((int)$f['supervisor_id'] === $uid) { $myIds[] = (int)$f['id']; continue; }
        $lid = null; foreach ($letters as $L) { if ($L['code'] === (string)$f['legacy_mother_first_letter'] || normalize_arabic_letter($L['code']) === normalize_arabic_letter((string)$f['legacy_mother_first_letter'])) { $lid = (int)$L['id']; break; } }
        if ($lid !== null && in_array($lid, $myLetterIds, true)) $myIds[] = (int)$f['id'];
    }
}
if ($role === 'nanny') $myIds = array_map('intval', array_column(dbFetchAll("SELECT id FROM families WHERE nanny_id = ?", [$uid]), 'id'));
$all = dbFetchAll("SELECT f.id, f.family_code, f.mother_name, f.mother_phone, f.status, f.children_count, f.nanny_id,
    n.full_name AS nanny_name,
    (SELECT COUNT(*) FROM family_children fc WHERE fc.family_id = f.id) AS actual_children_count,
    (SELECT COUNT(*) FROM sponsorships sp WHERE sp.status = 'active' AND sp.child_id IN (SELECT fc.id FROM family_children fc WHERE fc.family_id = f.id)) AS active_sponsorships,
    (SELECT COALESCE(SUM(sp.monthly_amount),0) FROM sponsorships sp WHERE sp.status = 'active' AND sp.child_id IN (SELECT fc.id FROM family_children fc WHERE fc.family_id = f.id)) AS monthly_commitment
    FROM families f LEFT JOIN users n ON n.id = f.nanny_id");
$filtered = [];
foreach ($all as $row) {
    if ($myIds !== null && !in_array((int)$row['id'], $myIds, true)) continue;
    if ($fStatus !== '' && $row['status'] !== $fStatus) continue;
    if ($nq !== '') { $codeHay = mb_strtolower((string)$row['family_code'] . ' ' . (string)$row['mother_phone'], 'UTF-8'); if (!(str_starts_with($norm((string)$row['mother_name']), $nq) || mb_strpos($codeHay, $nq, 0, 'UTF-8') !== false)) continue; }
    $filtered[] = $row;
}
$total = count($filtered); $pages = max(1, (int)ceil($total / $perPage)); $page = min($page, $pages); $rows = array_slice($filtered, ($page - 1) * $perPage, $perPage); $qs = fn(array $extra) => APP_URL . 'modules/families/index.php?' . http_build_query(array_merge($_GET, $extra));
$canDeleteFamily = in_array($role, ['admin', 'vice_general_manager'], true);
include dirname(__DIR__, 2) . '/includes/header.php'; ?>
<style>
.families-table-wrap { overflow-x: auto; }
.families-table thead th { position: sticky; top: 0; z-index: 10; background-color: #212529; color: #fff; font-weight: 600; white-space: nowrap; border-bottom: 2px solid #495057; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.12); }
</style>
<div class="welcome-section fade-in"><h2><?php echo e(t('families.title')); ?></h2><p><?php echo e(t('families.count', ['count' => $total])); ?></p><div class="quick-actions mt-3"><?php if (in_array($role, ['admin', 'vice_general_manager', 'supervisor'], true)): ?><a href="<?php echo APP_URL; ?>modules/families/create.php" class="btn btn-primary btn-sm"><i class="fas fa-plus me-1"></i> <?php echo e(t('families.add')); ?></a><?php endif; ?></div></div>
<?php include dirname(__DIR__, 2) . '/includes/alerts.php'; ?>
<?php if ($role === 'nanny' && $total === 0): ?><div class="alert alert-info fade-in"><i class="fas fa-circle-info me-2"></i><?php echo e(t('families.nanny_empty')); ?></div><?php endif; ?>
<div class="card mb-3 fade-in"><div class="card-body"><form method="get" class="row g-2 align-items-end"><div class="col-md-6"><label class="form-label"><?php echo e(t('families.search_label')); ?> <small class="text-muted"><?php echo e(t('families.search_hint')); ?></small></label><input type="text" name="q" class="form-control" value="<?php echo e($q); ?>"></div><div class="col-md-3"><label class="form-label"><?php echo e(t('common.status')); ?></label><select name="status" class="form-select"><option value=""><?php echo e(t('common.all')); ?></option><option value="active" <?php echo $fStatus === 'active' ? 'selected' : ''; ?>><?php echo e(t('families.status_active')); ?></option><option value="pending" <?php echo $fStatus === 'pending' ? 'selected' : ''; ?>><?php echo e(t('families.status_pending')); ?></option><option value="paused" <?php echo $fStatus === 'paused' ? 'selected' : ''; ?>><?php echo e(t('families.status_paused')); ?></option><option value="completed" <?php echo $fStatus === 'completed' ? 'selected' : ''; ?>><?php echo e(t('families.status_completed')); ?></option><option value="archived" <?php echo $fStatus === 'archived' ? 'selected' : ''; ?>><?php echo e(t('families.status_archived')); ?></option></select></div><div class="col-md-3"><button class="btn btn-primary w-100"><i class="fas fa-search me-1"></i> <?php echo e(t('common.search')); ?></button></div></form></div></div>
<div class="card fade-in"><div class="card-body p-0"><div class="table-responsive families-table-wrap"><table class="table table-hover align-middle mb-0 families-table"><thead><tr><th><?php echo e(t('families.code')); ?></th><th><?php echo e(t('families.mother_name')); ?></th><th><?php echo e(t('families.phone')); ?></th><th><?php echo e(t('families.orphans')); ?></th><th><?php echo e(t('families.active_sponsorships')); ?></th><th><?php echo e(t('families.monthly_commitment')); ?></th><th><?php echo e(t('families.specialist')); ?></th><th><?php echo e(t('common.status')); ?></th><th class="text-center"><?php echo e(t('common.actions')); ?></th></tr></thead><tbody><?php if (!$rows): ?><tr><td colspan="9" class="text-center text-muted py-4"><?php echo e(t('families.no_results')); ?></td></tr><?php else: foreach ($rows as $r): $st = ['active'=>['families.status_active','bg-success'],'pending'=>['families.status_pending','bg-warning text-dark'],'paused'=>['families.status_paused','bg-warning text-dark'],'completed'=>['families.status_completed','bg-info'],'archived'=>['families.status_archived','bg-secondary'],'inactive'=>['families.status_inactive','bg-secondary'],'closed'=>['families.status_closed','bg-dark']]; [$sk,$sc] = $st[$r['status']] ?? [$r['status'],'bg-secondary']; $childCount = (int)$r['actual_children_count']; ?>
<tr><td><?php echo e($r['family_code']); ?></td><td><strong><?php echo e($r['mother_name']); ?></strong></td><td dir="ltr"><?php echo e($r['mother_phone'] ?? '-'); ?></td><td><?php echo $childCount; ?></td><td><?php echo (int)$r['active_sponsorships']; ?></td><td><?php echo number_format((float)$r['monthly_commitment'], 0); ?></td><td><?php echo e($r['nanny_name'] ?? '—'); ?></td><td><span class="badge <?php echo $sc; ?>"><?php echo e(t($sk)); ?></span></td><td class="text-center" style="white-space:nowrap;"><a class="btn btn-sm btn-primary" title="<?php echo e(t('common.view')); ?>" href="<?php echo APP_URL; ?>modules/families/view.php?id=<?php echo (int)$r['id']; ?>"><i class="fas fa-eye"></i></a><?php if ($role !== 'general_manager'): ?><a class="btn btn-sm btn-warning" title="<?php echo e(t('common.edit')); ?>" href="<?php echo APP_URL; ?>modules/families/edit.php?id=<?php echo (int)$r['id']; ?>"><i class="fas fa-pen"></i></a><?php endif; ?><?php if ($canDeleteFamily && $childCount === 0): ?><button type="button" class="btn btn-sm btn-danger" title="<?php echo e(t('families.delete_family')); ?>" data-bs-toggle="modal" data-bs-target="#deleteFamilyModal" data-family-id="<?php echo (int)$r['id']; ?>" data-family-code="<?php echo e($r['family_code']); ?>" data-mother-name="<?php echo e($r['mother_name']); ?>"><i class="fas fa-trash"></i></button><?php endif; ?></td></tr>
<?php endforeach; endif; ?></tbody></table></div></div></div>
<?php if ($pages > 1): ?>
<nav class="mt-3 mb-4" aria-label="<?php echo e(t('families.pages_label')); ?>"><ul class="pagination justify-content-center flex-wrap gap-1" style="row-gap:.35rem;"><li class="page-item <?php echo $page <= 1 ? 'disabled' : ''; ?>"><a class="page-link" href="<?php echo $page <= 1 ? '#' : e($qs(['page'=>1])); ?>" aria-label="<?php echo e(t('families.first_page')); ?>"><?php echo e(t('families.first_page')); ?></a></li><li class="page-item <?php echo $page <= 1 ? 'disabled' : ''; ?>"><a class="page-link" href="<?php echo $page <= 1 ? '#' : e($qs(['page'=>$page-1])); ?>" aria-label="<?php echo e(t('common.previous')); ?>"><?php echo e(t('common.previous')); ?></a></li><?php $startPage = max(1, $page - 2); $endPage = min($pages, $page + 2); if ($page <= 3) $endPage = min($pages, 5); if ($page >= $pages - 2) $startPage = max(1, $pages - 4); if ($startPage > 1): ?><li class="page-item"><a class="page-link" href="<?php echo e($qs(['page'=>1])); ?>">1</a></li><?php if ($startPage > 2): ?><li class="page-item disabled"><span class="page-link">…</span></li><?php endif; ?><?php endif; ?><?php for ($i = $startPage; $i <= $endPage; $i++): ?><li class="page-item <?php echo $i === $page ? 'active' : ''; ?>"><a class="page-link" href="<?php echo e($qs(['page'=>$i])); ?>"><?php echo $i; ?></a></li><?php endfor; ?><?php if ($endPage < $pages): ?><?php if ($endPage < $pages - 1): ?><li class="page-item disabled"><span class="page-link">…</span></li><?php endif; ?><li class="page-item"><a class="page-link" href="<?php echo e($qs(['page'=>$pages])); ?>"><?php echo $pages; ?></a></li><?php endif; ?><li class="page-item <?php echo $page >= $pages ? 'disabled' : ''; ?>"><a class="page-link" href="<?php echo $page >= $pages ? '#' : e($qs(['page'=>$page+1])); ?>" aria-label="<?php echo e(t('common.next')); ?>"><?php echo e(t('common.next')); ?></a></li><li class="page-item <?php echo $page >= $pages ? 'disabled' : ''; ?>"><a class="page-link" href="<?php echo $page >= $pages ? '#' : e($qs(['page'=>$pages])); ?>" aria-label="<?php echo e(t('families.last_page')); ?>"><?php echo e(t('families.last_page')); ?></a></li></ul></nav>
<?php endif; ?>
<?php if ($canDeleteFamily): ?>
<div class="modal fade" id="deleteFamilyModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title text-danger"><i class="fas fa-triangle-exclamation me-2"></i><?php echo e(t('families.delete_title')); ?></h5><button type="button" class="btn-close ms-0" data-bs-dismiss="modal" aria-label="<?php echo e(t('common.close')); ?>"></button></div><div class="modal-body"><p class="mb-2"><?php echo e(t('families.delete_question')); ?></p><div class="alert alert-warning mb-0"><strong id="deleteFamilyLabel"></strong><br><small><?php echo e(t('families.delete_note')); ?></small></div></div><div class="modal-footer"><form method="post" action="<?php echo APP_URL; ?>modules/families/delete.php" class="m-0"><?php echo csrf_field(); ?><input type="hidden" name="family_id" id="deleteFamilyId" value=""><button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><?php echo e(t('common.cancel')); ?></button><button type="submit" class="btn btn-danger"><i class="fas fa-trash me-1"></i><?php echo e(t('families.delete_yes')); ?></button></form></div></div></div></div>
<script>
document.addEventListener('DOMContentLoaded', function () { var modal = document.getElementById('deleteFamilyModal'); if (!modal) return; modal.addEventListener('show.bs.modal', function (event) { var button = event.relatedTarget; if (!button) return; document.getElementById('deleteFamilyId').value = button.getAttribute('data-family-id') || ''; document.getElementById('deleteFamilyLabel').textContent = (button.getAttribute('data-family-code') || '') + ' — ' + (button.getAttribute('data-mother-name') || ''); }); });
</script>
<?php endif; ?>
<?php include dirname(__DIR__, 2) . '/includes/footer.php'; ?>
