<?php
// Quick access: search & open/print orphan forms (role-scoped)
error_reporting(E_ALL); ini_set('display_errors', '1');
require_once dirname(__DIR__, 2) . '/config/config.php'; require_once dirname(__DIR__, 2) . '/config/database.php'; require_once dirname(__DIR__, 2) . '/config/functions.php'; require_once dirname(__DIR__, 2) . '/config/session.php';
Session::start();
if (!Session::isLoggedIn()) { header('Location: ' . APP_URL . 'index.php'); exit(); }
$role=Session::getUserRole(); $viewRoles=['admin','vice_general_manager','general_manager','supervisor','nanny','accountant','accountant_staff','administration','social_media'];
if(!in_array($role,$viewRoles,true)){header('Location: '.APP_URL.'index.php');exit();}
$uid=(int)Session::getUserId(); $canEdit=in_array($role,['admin','vice_general_manager','supervisor','nanny'],true); $canSeeFinancial=in_array($role,['admin','vice_general_manager','general_manager','supervisor','nanny'],true);
$pageTitle=t('forms.orphan_title'); $active='orphan_forms'; $q=trim((string)($_GET['q']??'')); $search=mb_substr($q,0,60);
$scopeSql='';$params=[];
if($role==='nanny'){$scopeSql=' AND f.nanny_id = ? ';$params[]=$uid;}elseif($role==='supervisor'){$codes=[];try{$codes=array_map(fn($r)=>(string)$r['code'],dbFetchAll("SELECT l.code FROM supervisor_letters sl JOIN letters l ON l.id = sl.letter_id WHERE sl.supervisor_id = ?",[$uid]));}catch(Throwable $ex){}$scopeSql=' AND ( f.supervisor_id = ? ';$params[]=$uid;if($codes&&function_exists('normalize_arabic_letter')){$norm=array_values(array_unique(array_map(fn($c)=>normalize_arabic_letter($c),$codes)));if($norm){$ph=implode(',',array_fill(0,count($norm),'?'));$scopeSql.=" OR f.legacy_mother_first_letter IN ($ph) ";foreach($norm as $n)$params[]=$n;}}$scopeSql.=' ) ';}
$searchSql='';if($search!==''){$like='%'.$search.'%';$searchSql=' AND ( fc.child_name LIKE ? OR f.mother_name LIKE ? OR f.family_code LIKE ? OR fc.form_serial LIKE ? ) ';$params[]=$like;$params[]=$like;$params[]=$like;$params[]=$like;}
$sql="SELECT fc.id, fc.child_name, fc.gender, fc.form_serial, f.family_code, f.mother_name, f.status AS family_status FROM family_children fc JOIN families f ON f.id = fc.family_id WHERE 1=1".$scopeSql.$searchSql." ORDER BY fc.id DESC LIMIT 200";
$rows=dbFetchAll($sql,$params);
$akCss='#ak-ofi-page{--navy:#1b4d8f;--line:#e3e8ef;--muted:#6b7280;font-size:.95rem}#ak-ofi-page .ak-head{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:14px}#ak-ofi-page .ak-title{font-size:1.3rem;font-weight:800;color:var(--navy);margin:0}#ak-ofi-page .ak-card{background:#fff;border:1px solid var(--line);border-radius:12px;margin-bottom:16px;overflow:hidden}#ak-ofi-page .ak-card-head{background:var(--navy);color:#fff;padding:10px 14px;font-weight:700;font-size:.9rem}#ak-ofi-page .ak-table{width:100%;border-collapse:collapse;background:#fff}#ak-ofi-page .ak-table th{background:var(--navy);color:#fff;font-weight:600;font-size:.83rem;padding:10px 12px;text-align:right}#ak-ofi-page .ak-table td{padding:9px 12px;border-bottom:1px solid var(--line);font-size:.88rem;vertical-align:middle}#ak-ofi-page .ak-table tr:hover td{background:#f8fafc}#ak-ofi-page .ak-btn{border:0;border-radius:8px;padding:6px 12px;font-size:.8rem;font-weight:700;cursor:pointer;text-decoration:none;display:inline-block}#ak-ofi-page .ak-btn-navy{background:var(--navy);color:#fff}#ak-ofi-page .ak-btn-green{background:#16a34a;color:#fff}#ak-ofi-page .ak-btn-ghost{background:#fff;border:1px solid var(--line);color:#374151}#ak-ofi-page .ak-btn-ghost:hover{background:#f3f4f6}#ak-ofi-page .ak-input{border:1px solid var(--line);border-radius:8px;padding:7px 12px;font-size:.9rem;background:#fff;color:#111827}#ak-ofi-page .ak-badge{border-radius:99px;padding:3px 10px;font-size:.72rem;font-weight:700;display:inline-block}#ak-ofi-page .ak-b-green{background:#dcfce7;color:#166534}#ak-ofi-page .ak-b-gray{background:#e5e7eb;color:#374151}';
$akHeader=dirname(__DIR__,2).'/includes/header.php';$akFooter=dirname(__DIR__,2).'/includes/footer.php';$useLayout=is_file($akHeader)&&is_file($akFooter);
if($useLayout){require $akHeader;echo '<main id="ak-ofi-page" class="container-fluid py-4"><style>'.$akCss.'</style>';}else{echo '<!DOCTYPE html><html lang="ar" dir="rtl"><head><meta charset="UTF-8"><title>'.e(t('forms.orphan_title')).'</title></head><body style="background:#f4f7fb"><main id="ak-ofi-page" class="container-fluid py-4"><style>'.$akCss.'</style>';}
?>
<div class="ak-head"><div><h1 class="ak-title"><?php echo e(t('forms.orphan_title')); ?> — <?php echo e(t('forms.view_print')); ?></h1><div style="color:#6b7280;font-size:.82rem"><?php echo e(t('forms.orphan_subtitle')); ?></div></div><form method="get" style="display:flex;gap:6px"><input type="text" name="q" class="ak-input" style="min-width:260px" placeholder="<?php echo e(t('forms.search_placeholder')); ?>" value="<?= e($search) ?>"><button class="ak-btn ak-btn-navy" type="submit"><?php echo e(t('common.search')); ?></button><a class="ak-btn ak-btn-ghost" href="<?= APP_URL; ?>modules/families/orphan_forms_index.php"><?php echo e(t('forms.clear')); ?></a></form></div>
<div class="ak-card"><div class="ak-card-head"><?php echo e(t('forms.results',['count'=>count($rows)])); ?><?= $search === '' ? ' — '.e(t('forms.latest_scope')) : '' ?></div><div style="overflow-x:auto"><table class="ak-table"><thead><tr><th>#</th><th><?php echo e(t('forms.orphan')); ?></th><th><?php echo e(t('forms.family')); ?></th><th><?php echo e(t('forms.mother')); ?></th><th><?php echo e(t('forms.form_number')); ?></th><th><?php echo e(t('forms.actions')); ?></th></tr></thead><tbody>
<?php if(!$rows): ?><tr><td colspan="6" style="text-align:center;color:#6b7280;padding:24px"><?php echo e(t('forms.no_results')); ?></td></tr><?php endif; ?>
<?php foreach($rows as $r): ?><tr><td><?= (int)$r['id'] ?></td><td><strong><?= e($r['child_name']) ?></strong></td><td><?= e($r['family_code']) ?></td><td><?= e($r['mother_name']) ?></td><td><?= $r['form_serial']?'<span class="ak-badge ak-b-green">'.e($r['form_serial']).'</span>':'<span class="ak-badge ak-b-gray">'.e(t('forms.no_number')).'</span>' ?></td><td><div style="display:flex;gap:6px;flex-wrap:wrap"><a class="ak-btn ak-btn-navy" target="_blank" href="<?= APP_URL; ?>modules/families/orphan_form.php?child=<?= (int)$r['id'] ?>"><?php echo e(t('forms.view_print')); ?></a><?php if($canEdit): ?><a class="ak-btn ak-btn-green" href="<?= APP_URL; ?>modules/families/orphan_form.php?child=<?= (int)$r['id'] ?>&tab=edit"><?php echo e(t('forms.fill_data')); ?></a><?php endif; ?><?php if($canSeeFinancial): ?><a class="ak-btn ak-btn-ghost" href="<?= APP_URL; ?>modules/families/orphan_profile.php?child=<?= (int)$r['id'] ?>"><?php echo e(t('forms.financial_profile')); ?></a><?php endif; ?></div></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php if($useLayout){echo '</main>';require $akFooter;}else{echo '</main></body></html>';}