<?php
// modules/families/view.php - Family profile (bank accounts + children + sponsorships) — Orphan-level pivot
require_once dirname(__DIR__, 2) . '/config/config.php';
require_once dirname(__DIR__, 2) . '/config/database.php';
require_once dirname(__DIR__, 2) . '/config/functions.php';
require_once dirname(__DIR__, 2) . '/config/session.php';
Session::start();
if (!Session::isLoggedIn()) { header('Location: ' . APP_URL . 'index.php'); exit(); }
$role = Session::getUserRole();
if (!in_array($role, ['admin', 'vice_general_manager', 'general_manager', 'supervisor', 'nanny'], true)) { header('Location: ' . APP_URL . 'index.php'); exit(); }
$pageTitle='ملف الأسرة'; $active='families'; $uid=Session::getUserId(); $id=(int)($_GET['id']??0);
$fam=dbFetchOne("SELECT f.*, n.full_name AS nanny_name, s.full_name AS supervisor_name FROM families f LEFT JOIN users n ON n.id=f.nanny_id LEFT JOIN users s ON s.id=f.supervisor_id WHERE f.id=?",[$id]); if(!$fam){flash('error','الأسرة غير موجودة.');redirect('modules/families/index.php');}
if($role==='nanny'&&(int)($fam['nanny_id']??0)!==$uid){flash('error','هذه الأسرة ليست ضمن نطاقك.');redirect('modules/families/index.php');}
if($role==='supervisor'&&!ak_family_user_in_scope($fam,$role,$uid)){flash('error','هذه الأسرة ليست ضمن نطاقك.');redirect('modules/families/index.php');}
$children=dbFetchAll("SELECT fc.*, CASE WHEN EXISTS (SELECT 1 FROM sponsorships sp WHERE sp.child_id=fc.id AND sp.status='active') THEN 'matched' ELSE fc.match_status END AS display_match_status FROM family_children fc WHERE fc.family_id=? ORDER BY fc.birth_date DESC",[$id]);$bankAccounts=dbFetchAll("SELECT * FROM family_bank_accounts WHERE family_id=? ORDER BY is_primary DESC,id ASC",[$id]);$ships=dbFetchAll("SELECT sp.*,s.full_name AS sponsor_name,s.sponsor_code,fc.child_name FROM sponsorships sp JOIN sponsors s ON s.id=sp.sponsor_id JOIN family_children fc ON fc.id=sp.child_id WHERE fc.family_id=? ORDER BY sp.id DESC",[$id]);$totalMonthly=0;foreach($ships as $s)if($s['status']==='active')$totalMonthly+=(float)$s['monthly_amount'];$waitingChildren=0;$matchedChildren=0;foreach($children as $c){if(($c['display_match_status']??'unmatched')==='matched')$matchedChildren++;else$waitingChildren++;}$gLabel=['male'=>'ذكر','female'=>'أنثى','unknown'=>'غير معروف'];$mBadge=['matched'=>['مكفول','bg-success'],'waiting_list'=>['في الانتظار','bg-info'],'lost_sponsor'=>['فقد كفيله','bg-warning text-dark'],'unmatched'=>['غير مكفول','bg-secondary']];include dirname(__DIR__,2).'/includes/header.php'; ?>
<div class="welcome-section fade-in"><h2><?php echo e($fam['mother_name']); ?></h2><p><?php echo e($fam['family_code']); ?> · <?php echo e($fam['status']); ?></p><div class="quick-actions mt-3" style="position:static;margin-bottom:1.25rem;"><a href="<?php echo APP_URL; ?>modules/families/index.php" class="btn btn-secondary btn-sm"><i class="fas fa-arrow-right me-1"></i> رجوع</a><?php if($role!=='general_manager'): ?><a href="<?php echo APP_URL; ?>modules/families/edit.php?id=<?php echo $id; ?>" class="btn btn-warning btn-sm"><i class="fas fa-pen me-1"></i> تعديل</a><?php endif; ?><a href="<?php echo APP_URL; ?>modules/families/documents.php?id=<?php echo $id; ?>" class="btn btn-info btn-sm"><i class="fas fa-folder-open me-1"></i> الوثائق</a></div></div>
<?php include dirname(__DIR__,2).'/includes/alerts.php'; ?>
<div class="row g-3 mt-3 mb-4 fade-in"><div class="col-md-3"><div class="card text-center"><div class="card-body py-2"><div class="fs-4 fw-bold" style="color:#1b4d8f"><?php echo count($children); ?></div><div class="text-muted small">الأطفال</div></div></div></div><div class="col-md-3"><div class="card text-center"><div class="card-body py-2"><div class="fs-4 fw-bold" style="color:#1b4d8f"><?php echo $matchedChildren; ?></div><div class="text-muted small">أيتام مكفولون</div></div></div></div><div class="col-md-3"><div class="card text-center"><div class="card-body py-2"><div class="fs-4 fw-bold" style="color:#1b4d8f"><?php echo $waitingChildren; ?></div><div class="text-muted small">بانتظار الكفالة</div></div></div></div><div class="col-md-3"><div class="card text-center"><div class="card-body py-2"><div class="fs-4 fw-bold" style="color:#1b4d8f"><?php echo number_format($totalMonthly,0); ?></div><div class="text-muted small">الالتزام الشهري النشط</div></div></div></div></div>
<div class="card mb-4 fade-in"><div class="card-header"><i class="fas fa-info-circle me-2"></i>بيانات الأسرة</div><div class="card-body"><div class="row"><div class="col-md-4"><small class="text-muted">هاتف الأم</small><div dir="ltr"><?php echo e($fam['mother_phone']??'-'); ?></div></div><div class="col-md-4"><small class="text-muted">هاتف بديل</small><div dir="ltr"><?php echo e($fam['mother_alt_phone']??'-'); ?></div></div><div class="col-md-4"><small class="text-muted">الرقم التسجيلي</small><div><?php echo e($fam['registration_number']??'-'); ?></div></div><div class="col-md-4 mt-2"><small class="text-muted">المدينة / الحي</small><div><?php echo e(trim((string)($fam['city']??''),' ')?:'-'); ?></div></div><div class="col-md-4 mt-2"><small class="text-muted">العنوان</small><div><?php echo e($fam['address']??'-'); ?></div></div><div class="col-md-4 mt-2"><small class="text-muted">الحالة الاجتماعية للأم</small><div><?php echo e($fam['mother_marital_status']??'أرملة'); ?></div></div><div class="col-md-4 mt-2"><small class="text-muted">اسم الأب</small><div><?php echo e($fam['father_name']??'-'); ?></div></div><div class="col-md-4 mt-2"><small class="text-muted">تاريخ وفاة الأب</small><div><?php echo e($fam['father_death_date']??'-'); ?></div></div><div class="col-md-4 mt-2"><small class="text-muted">سبب وفاة الأب</small><div><?php echo e($fam['father_death_cause']??'-'); ?></div></div><div class="col-md-4 mt-2"><small class="text-muted">المشرف</small><div><?php echo e($fam['supervisor_name']??'-'); ?></div></div><div class="col-md-4 mt-2"><small class="text-muted">الأخصائية</small><div><?php echo e($fam['nanny_name']??'-'); ?></div></div><div class="col-md-4 mt-2"><small class="text-muted">الاحتياج الشهري</small><div><?php echo number_format((float)($fam['monthly_need_amount']??0),0); ?></div></div><?php if(!empty($fam['notes'])):?><div class="col-12 mt-2"><small class="text-muted">ملاحظات</small><div><?php echo e($fam['notes']); ?></div></div><?php endif; ?></div></div></div>
<div class="card mb-4 fade-in"><div class="card-header"><i class="fas fa-children me-2"></i>الأطفال (<?php echo count($children); ?>)</div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>الاسم</th><th>الجنس</th><th>تاريخ الميلاد</th><th>حالة الكفالة</th><th>أولوية</th><th class="text-center">إجراءات</th></tr></thead><tbody><?php if(!$children): ?><tr><td colspan="6" class="text-center text-muted py-3">لا يوجد أطفال مسجلون.</td></tr><?php else:foreach($children as $c):[$mbL,$mbC]=$mBadge[$c['display_match_status']??'unmatched']??['—','bg-secondary']; ?><tr><td><strong><?php echo e($c['child_name']); ?></strong></td><td><?php echo e($gLabel[$c['gender']??'unknown']??'غير معروف'); ?></td><td><?php echo e($c['birth_date']??'-'); ?></td><td><span class="badge <?php echo $mbC; ?>"><?php echo $mbL; ?></span></td><td><?php echo((int)($c['is_critical']??0)===1)?'<span class="badge bg-danger">حالة حرجة</span>':'—'; ?></td><td class="text-center" style="white-space:nowrap;"><a class="btn btn-sm btn-primary" title="ملف اليتيم" href="<?php echo APP_URL; ?>modules/families/orphan_profile.php?id=<?php echo(int)$c['id']; ?>"><i class="fas fa-eye"></i></a><?php if($role!=='general_manager'): ?><a class="btn btn-sm btn-info" title="نموذج اليتيم" href="<?php echo APP_URL; ?>modules/families/orphan_form.php?id=<?php echo(int)$c['id']; ?>"><i class="fas fa-file-pen"></i></a><?php endif; ?></td></tr><?php endforeach;endif; ?></tbody></table></div></div></div>
<?php if($bankAccounts): ?><div class="card mb-4 fade-in"><div class="card-header"><i class="fas fa-building-columns me-2"></i>الحسابات البنكية</div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>البنك</th><th>رقم الحساب</th><th>صاحب الحساب</th><th>أساسي</th></tr></thead><tbody><?php foreach($bankAccounts as $b): ?><tr><td><?php echo e($b['bank_name']??($b['bank']??'-')); ?></td><td dir="ltr"><?php echo e($b['account_number']??($b['bank_account_number']??'-')); ?></td><td><?php echo e($b['account_holder']??($b['bank_account_holder']??'-')); ?></td><td><?php echo((int)($b['is_primary']??0)===1)?'<span class="badge bg-success">نعم</span>':'—'; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div><?php endif; ?>
<div class="card fade-in"><div class="card-header"><i class="fas fa-hand-holding-heart me-2"></i>الكفالات (<?php echo count($ships); ?>)</div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>الكود</th><th>الكفيل</th><th>اليتيم</th><th>المبلغ الشهري</th><th>البداية</th><th>الحالة</th><th></th></tr></thead><tbody><?php if(!$ships): ?><tr><td colspan="7" class="text-center text-muted py-3">لا توجد كفالات لهذه الأسرة.</td></tr><?php else:foreach($ships as $s):$st=['active'=>['نشطة','bg-success'],'paused'=>['متوقفة','bg-warning text-dark'],'completed'=>['مكتملة','bg-info'],'cancelled'=>['ملغية','bg-danger']];[$sl,$sc]=$st[$s['status']]??[$s['status'],'bg-secondary']; ?><tr><td><?php echo e($s['sponsorship_code']); ?></td><td><?php echo e($s['sponsor_name']); ?> <small class="text-muted">(<?php echo e($s['sponsor_code']); ?>)</small></td><td><strong><?php echo e($s['child_name']); ?></strong></td><td><?php echo number_format((float)$s['monthly_amount'],0); ?></td><td><?php echo e($s['start_date']); ?></td><td><span class="badge <?php echo $sc; ?>"><?php echo $sl; ?></span></td><td><a class="btn btn-sm btn-primary" href="<?php echo APP_URL; ?>modules/sponsorships/view.php?id=<?php echo(int)$s['id']; ?>"><i class="fas fa-eye"></i></a></td></tr><?php endforeach;endif; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__,2).'/includes/footer.php'; ?>