<?php
/** Financial Manager dashboard UI catalog. Stable translation keys only. */
return [
    'fm.page_title' => 'لوحة المدير المالي', 'fm.welcome' => 'مرحباً، المدير المالي', 'fm.overview' => 'نظرة شاملة على الخزينة والتدفقات المالية — :date',
    'fm.cash' => 'الصندوق النقدي', 'fm.bank' => 'الحساب البنكي', 'fm.wallet' => 'المحفظة الإلكترونية', 'fm.total_treasury' => 'إجمالي الخزينة', 'fm.account_1100' => 'حساب 1100', 'fm.account_1200' => 'حساب 1200', 'fm.account_1300' => 'حساب 1300', 'fm.currency_sdg' => 'ج.س',
    'fm.project_budget_review' => 'ميزانيات المشاريع بانتظار المراجعة المالية', 'fm.request_count' => ':count طلب', 'fm.no_project_budgets' => 'لا توجد ميزانيات مشاريع بانتظار المراجعة المالية.', 'fm.project' => 'المشروع', 'fm.project_type' => 'النوع', 'fm.created_by' => 'أنشأه', 'fm.budget' => 'الميزانية', 'fm.items' => 'البنود', 'fm.submission_date' => 'تاريخ الإرسال', 'fm.transfer_date' => 'تاريخ التحويل', 'fm.funding_source_distribution' => 'توزيع مصادر التمويل من قبل المدير المالي', 'fm.action' => 'الإجراء', 'fm.version' => 'نسخة :version', 'fm.available' => 'متاح :amount', 'fm.amount_from_account' => 'المبلغ من هذا الحساب', 'fm.view_project' => 'عرض المشروع', 'fm.financial_approval' => 'اعتماد مالي', 'fm.reject' => 'رفض', 'fm.approve_project_confirm' => 'اعتماد ميزانية هذا المشروع بعد حفظ توزيع مصادر التمويل؟', 'fm.reject_reason_prompt' => 'اكتب سبب رفض الميزانية:',
    'fm.monthly_income' => 'إيرادات الشهر (:month)', 'fm.monthly_expenses' => 'مصروفات الشهر (:month)', 'fm.income' => 'دخل', 'fm.outgoing' => 'خرج', 'fm.total_income' => 'إجمالي الإيرادات', 'fm.total_expenses' => 'إجمالي المصروفات', 'fm.cash_income' => 'نقداً (4100)', 'fm.bank_income' => 'بنكياً (4200)', 'fm.cash_expense' => 'نقداً (5100)', 'fm.bank_expense' => 'بنكياً (5200)', 'fm.net_monthly_flow' => 'صافي التدفق الشهري', 'fm.surplus' => 'فائض', 'fm.deficit' => 'عجز', 'fm.net_result' => 'الصافي (:status)',
    'fm.monthly_disbursement_status' => 'حالة الدفعات الشهرية', 'fm.view_all' => 'عرض الكل', 'fm.pending_approval' => 'بانتظار الاعتماد', 'fm.transferred_open' => 'محوّلة (مفتوحة)', 'fm.received_closed' => 'مستلمة (مغلقة)', 'fm.fully_disbursed' => 'تم الصرف الكامل', 'fm.voided' => 'مُبطَلة', 'fm.posted_reversal' => 'قيد عكسي مُرحّل', 'fm.disbursement_approval_queue' => 'طابور اعتماد الدفعات — :count دفعة بانتظار مراجعتك', 'fm.review' => 'مراجعة', 'fm.open_disbursements' => 'دفعات مفتوحة — بانتظار صرف الأخصائيات', 'fm.disbursement_count' => ':count دفعة', 'fm.nanny' => 'الأخصائية', 'fm.days_open' => 'أيام مفتوحة', 'fm.details' => 'تفاصيل', 'fm.paid_count' => ':count مُصرَف', 'fm.pending_count' => ':count معلّق', 'fm.return_count' => ':count إرجاع', 'fm.day_count' => ':count يوم',
    'fm.recent_returns' => 'آخر عمليات الإرجاع', 'fm.entry' => 'القيد', 'fm.family' => 'الأسرة', 'fm.recent_voided' => 'آخر الدفعات المُبطَلة', 'fm.reason' => 'السبب', 'fm.quick_stats' => 'إحصائيات سريعة', 'fm.active_sponsorships' => 'كفالة نشطة', 'fm.active_families' => 'أسرة نشطة', 'fm.active_nannies' => 'أخصائية نشطة', 'fm.disbursed_this_month' => 'مُصرَف هذا الشهر', 'fm.recent_journals' => 'آخر القيود المحاسبية', 'fm.entry_number' => 'رقم القيد', 'fm.date' => 'التاريخ', 'fm.description' => 'الوصف', 'fm.debit' => 'مدين', 'fm.credit' => 'دائن', 'fm.status' => 'الحالة', 'fm.status_posted' => 'مرحّل', 'fm.status_voided' => 'مُبطَل',
    'fm.unauthorized' => 'غير مصرح لك بعرض هذه الصفحة.', 'fm.session_expired' => 'انتهت صلاحية الجلسة.', 'fm.approval_fm_only' => 'اعتماد ميزانية المشروع متاح للمدير المالي فقط.', 'fm.project_not_in_queue' => 'المشروع غير موجود في طابور المراجعة المالية.', 'fm.invalid_review_decision' => 'قرار المراجعة غير صالح.', 'fm.rejection_reason_required' => 'سبب رفض الميزانية مطلوب.', 'fm.invalid_funding_account' => 'حساب مصدر التمويل غير صالح.', 'fm.insufficient_balance' => 'الرصيد المتاح غير كافٍ في الحساب :code. المتاح: :amount', 'fm.funding_total_mismatch' => 'يجب أن يساوي مجموع مصادر التمويل الميزانية المقترحة: :amount', 'fm.no_budget_amount' => 'لا يمكن اعتماد مشروع دون مبلغ ميزانية مقترح.', 'fm.approved_success' => 'تم اعتماد ميزانية المشروع مبدئياً، وأصبح المشروع جاهزاً للاعتماد النهائي من المدير العام.', 'fm.rejected_success' => 'تم رفض ميزانية المشروع وإعادتها إلى مدير المشاريع.',
];
