<?php
/** Financial Manager dashboard UI catalog. Stable translation keys only. */
return [
    'fm.page_title' => 'Financial Manager Dashboard', 'fm.welcome' => 'Welcome, Financial Manager', 'fm.overview' => 'Overview of treasury and financial flows — :date',
    'fm.cash' => 'Cash on Hand', 'fm.bank' => 'Bank Account', 'fm.wallet' => 'Electronic Wallet', 'fm.total_treasury' => 'Total Treasury', 'fm.account_1100' => 'Account 1100', 'fm.account_1200' => 'Account 1200', 'fm.account_1300' => 'Account 1300', 'fm.currency_sdg' => 'SDG',
    'fm.project_budget_review' => 'Project Budgets Pending Financial Review', 'fm.request_count' => ':count Request(s)', 'fm.no_project_budgets' => 'No project budgets are pending financial review.', 'fm.project' => 'Project', 'fm.project_type' => 'Type', 'fm.created_by' => 'Created By', 'fm.budget' => 'Budget', 'fm.items' => 'Items', 'fm.submission_date' => 'Submission Date', 'fm.transfer_date' => 'Transfer Date', 'fm.funding_source_distribution' => 'Funding Source Distribution by Financial Manager', 'fm.action' => 'Action', 'fm.version' => 'Version :version', 'fm.available' => 'Available :amount', 'fm.amount_from_account' => 'Amount from this account', 'fm.view_project' => 'View Project', 'fm.financial_approval' => 'Financial Approval', 'fm.reject' => 'Reject', 'fm.approve_project_confirm' => 'Approve this project budget after saving the funding source distribution?', 'fm.reject_reason_prompt' => 'Enter the budget rejection reason:',
    'fm.monthly_income' => 'Monthly Income (:month)', 'fm.monthly_expenses' => 'Monthly Expenses (:month)', 'fm.income' => 'Income', 'fm.outgoing' => 'Outgoing', 'fm.total_income' => 'Total Income', 'fm.total_expenses' => 'Total Expenses', 'fm.cash_income' => 'Cash (4100)', 'fm.bank_income' => 'Bank (4200)', 'fm.cash_expense' => 'Cash (5100)', 'fm.bank_expense' => 'Bank (5200)', 'fm.net_monthly_flow' => 'Net Monthly Flow', 'fm.surplus' => 'Surplus', 'fm.deficit' => 'Deficit', 'fm.net_result' => 'Net (:status)',
    'fm.monthly_disbursement_status' => 'Monthly Disbursement Status', 'fm.view_all' => 'View All', 'fm.pending_approval' => 'Pending Approval', 'fm.transferred_open' => 'Transferred (Open)', 'fm.received_closed' => 'Received (Closed)', 'fm.fully_disbursed' => 'Fully Disbursed', 'fm.voided' => 'Voided', 'fm.posted_reversal' => 'Posted Reversal', 'fm.disbursement_approval_queue' => 'Disbursement Approval Queue — :count disbursement(s) awaiting your review', 'fm.review' => 'Review', 'fm.open_disbursements' => 'Open Disbursements — Awaiting Nanny Payout', 'fm.disbursement_count' => ':count disbursement(s)', 'fm.nanny' => 'Nanny', 'fm.days_open' => 'Days Open', 'fm.details' => 'Details', 'fm.paid_count' => ':count Paid', 'fm.pending_count' => ':count Pending', 'fm.return_count' => ':count Return(s)', 'fm.day_count' => ':count day(s)',
    'fm.recent_returns' => 'Recent Returns', 'fm.entry' => 'Entry', 'fm.family' => 'Family', 'fm.recent_voided' => 'Recent Voided Disbursements', 'fm.reason' => 'Reason', 'fm.quick_stats' => 'Quick Statistics', 'fm.active_sponsorships' => 'Active Sponsorships', 'fm.active_families' => 'Active Families', 'fm.active_nannies' => 'Active Nannies', 'fm.disbursed_this_month' => 'Disbursed This Month', 'fm.recent_journals' => 'Recent Journal Entries', 'fm.entry_number' => 'Entry Number', 'fm.date' => 'Date', 'fm.description' => 'Description', 'fm.debit' => 'Debit', 'fm.credit' => 'Credit', 'fm.status' => 'Status', 'fm.status_posted' => 'Posted', 'fm.status_voided' => 'Voided',
    'fm.unauthorized' => 'You are not authorized to view this page.', 'fm.session_expired' => 'Your session has expired.', 'fm.approval_fm_only' => 'Project budget approval is available to the Financial Manager only.', 'fm.project_not_in_queue' => 'The project is not in the financial review queue.', 'fm.invalid_review_decision' => 'Invalid review decision.', 'fm.rejection_reason_required' => 'A budget rejection reason is required.', 'fm.invalid_funding_account' => 'Invalid funding source account.', 'fm.insufficient_balance' => 'Insufficient available balance in account :code. Available: :amount', 'fm.funding_total_mismatch' => 'The total funding sources must equal the proposed budget: :amount', 'fm.no_budget_amount' => 'A project cannot be approved without a proposed budget amount.', 'fm.approved_success' => 'The project budget was provisionally approved and is now ready for final approval by the General Manager.', 'fm.rejected_success' => 'The project budget was rejected and returned to the Projects Manager.',
];
