<?php
// modules/accounting/accounts.php - Chart of Accounts
require_once dirname(__DIR__, 2) . '/config/config.php'; require_once dirname(__DIR__, 2) . '/config/database.php'; require_once dirname(__DIR__, 2) . '/config/functions.php'; require_once dirname(__DIR__, 2) . '/config/session.php'; require_once __DIR__ . '/lib.php';
Session::start();
if (!Session::isLoggedIn() || !in_array(Session::getUserRole(), ['admin','accountant','financial_manager','general_manager','vice_general_manager'], true)) { header('Location: ' . APP_URL . 'index.php'); exit(); }
$canManage = in_array(Session::getUserRole(), ['admin','accountant','financial_manager'], true); $pageTitle = t('navigation.chart_of_accounts'); $active = 'accounts'; ak_ensure_tables(); ak_seed_accounts();
$types = ['asset' => t('accounting.amount'), 'liability' => t('accounting.pending_outflows'), 'equity' => t('accounting.total_transactions'), 'revenue' => t('accounting.pending_income'), 'expense' => t('accounting.pending_outflows')];
$errors = [];
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $canManage) {
    if (!verify_csrf()) $errors[] = t('supervisors.session_expired');
    elseif (isset($_POST['add_account'])) {
        $code=trim($_POST['code']??''); $name=trim($_POST['name_ar']??''); $type=$_POST['account_type']??'';
        if (!preg_match('/^\d{3,6}$/',$code)) $errors[]='accounting.code_numeric';
        if ($name==='') $errors[]='accounting.name_required';
        if (!isset($types[$type])) $errors[]='accounting.type_invalid';
        if (!$errors && dbFetchOne("SELECT id FROM accounts WHERE code=?",[$code])) $errors[]='accounting.code_exists';
        if (!$errors) { dbExecute("INSERT INTO accounts (code,name_ar,name_en,account_type) VALUES (?,?,?,?)",[$code,$name,trim($_POST['name_en']??'')?:null,$type]); flash('success',t('accounting.account_added',['code'=>$code,'name'=>$name])); header('Location: '.APP_URL.'modules/accounting/accounts.php'); exit(); }
    } elseif (isset($_POST['toggle_account'])) {
        $id=(int)$_POST['toggle_account']; $a=dbFetchOne("SELECT id,is_active FROM accounts WHERE id=?",[$id]); if($a){dbExecute("UPDATE accounts SET is_active=? WHERE id=?",[(int)$a['is_active']?0:1,$id]);flash('success',t('accounting.status_updated'));} header('Location: '.APP_URL.'modules/accounting/accounts.php');exit();
    }
}
$accounts=dbFetchAll("SELECT a.*, (SELECT COALESCE(SUM(jl.debit-jl.credit),0) FROM journal_lines jl JOIN journal_entries je ON je.id=jl.entry_id WHERE jl.account_id=a.id AND je.status='posted') balance FROM accounts a ORDER BY a.code");
include dirname(__DIR__,2).'/includes/header.php'; ?>
<div class="welcome-section fade-in"><h2><?php echo e($pageTitle); ?></h2><p><?php echo e(t('accounting.dashboard_description')); ?></p></div>
<?php include dirname(__DIR__,2).'/includes/alerts.php'; ?>
<?php if($errors): ?><div class="alert alert-danger fade-in"><ul class="mb-0"><?php foreach($errors as $er) echo '<li>'.e(t($er)).'</li>'; ?></ul></div><?php endif; ?>
<?php if($canManage): ?><div class="card mb-4 fade-in"><div class="card-header"><i class="fas fa-plus me-2"></i><?php echo e(t('common.add')); ?></div><div class="card-body"><form method="post" class="row g-2"><?php echo csrf_field(); ?><div class="col-md-2"><input type="text" name="code" class="form-control" placeholder="<?php echo e(t('families.code')); ?> *" dir="ltr" required></div><div class="col-md-4"><input type="text" name="name_ar" class="form-control" placeholder="<?php echo e(t('supervisors.full_name')); ?> *" required></div><div class="col-md-3"><input type="text" name="name_en" class="form-control" placeholder="<?php echo e(t('common.language_en')); ?>" dir="ltr"></div><div class="col-md-2"><select name="account_type" class="form-select" required><?php foreach($types as $k=>$v): ?><option value="<?php echo e($k); ?>"><?php echo e($v); ?></option><?php endforeach; ?></select></div><div class="col-md-1"><button name="add_account" value="1" class="btn btn-primary w-100"><i class="fas fa-plus"></i></button></div></form></div></div><?php endif; ?>
<div class="card fade-in"><div class="card-body"><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th><?php echo e(t('families.code')); ?></th><th><?php echo e(t('supervisors.full_name')); ?></th><th><?php echo e(t('common.status')); ?></th><th><?php echo e(t('accounting.amount')); ?></th><th><?php echo e(t('common.status')); ?></th><?php if($canManage): ?><th class="text-center"><?php echo e(t('common.actions')); ?></th><?php endif; ?></tr></thead><tbody><?php foreach($accounts as $a): ?><tr><td><code><?php echo e($a['code']); ?></code></td><td><strong><?php echo e($a['name_ar']); ?></strong> <small class="text-muted"><?php echo e($a['name_en']??''); ?></small></td><td><span class="badge bg-light text-dark border"><?php echo e($types[$a['account_type']]??$a['account_type']); ?></span></td><td><?php echo number_format((float)$a['balance'],2); ?></td><td><?php echo (int)$a['is_active']===1?'<span class="badge bg-success">'.e(t('common.active')).'</span>':'<span class="badge bg-secondary">'.e(t('common.inactive')).'</span>'; ?></td><?php if($canManage): ?><td class="text-center"><form method="post" class="d-inline"><?php echo csrf_field(); ?><button name="toggle_account" value="<?php echo (int)$a['id']; ?>" class="btn btn-sm btn-outline-secondary" title="<?php echo e(t('common.status')); ?>"><i class="fas fa-toggle-on"></i></button></form></td><?php endif; ?></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__,2).'/includes/footer.php'; ?>