<?php
require_once dirname(__DIR__,2).'/config/config.php';
require_once dirname(__DIR__,2).'/config/database.php';
require_once dirname(__DIR__,2).'/config/functions.php';
require_once dirname(__DIR__,2).'/config/session.php';
require_once __DIR__.'/fina_lib.php';
Session::start();
if(!Session::isLoggedIn()){header('Location: '.APP_URL.'index.php');exit();}
$role=Session::getUserRole();
if(!in_array($role,['financial_manager','fm','supervisor','admin','vice_general_manager'],true)){header('Location: '.APP_URL.'index.php');exit();}
$uid=(int)Session::getUserId();$supervisorOwnOnly=($role==='supervisor');
fina_ensure_tables();
$pageTitle='تقرير تحصيلات فينا الخير';
$active='fina_report';
$from=trim($_GET['from']??date('Y-m-01'));$to=trim($_GET['to']??date('Y-m-d'));$currency=trim($_GET['currency']??'');
$validFrom=preg_match('/^\d{4}-\d{2}-\d{2}$/',$from);$validTo=preg_match('/^\d{4}-\d{2}-\d{2}$/',$to);if(!$validFrom)$from=date('Y-m-01');if(!$validTo)$to=date('Y-m-d');
$currencies=dbFetchAll("SELECT code FROM currencies ORDER BY code");
$where=['fc.collection_date BETWEEN ? AND ?'];$params=[$from,$to];if($supervisorOwnOnly){$where[]='fc.created_by=?';$params[]=$uid;}if($currency!==''){$where[]='fc.currency_code=?';$params[]=$currency;}
$summary=dbFetchAll("SELECT fc.currency_code,COUNT(*) total_count,COALESCE(SUM(fc.amount),0) total_amount,SUM(fc.status='pending') pending_count,COALESCE(SUM(CASE WHEN fc.status='pending' THEN fc.amount ELSE 0 END),0) pending_amount,SUM(fc.status='approved') approved_count,COALESCE(SUM(CASE WHEN fc.status='approved' THEN fc.amount ELSE 0 END),0) approved_amount,SUM(fc.status='returned') returned_count,COALESCE(SUM(CASE WHEN fc.status='returned' THEN fc.amount ELSE 0 END),0) returned_amount FROM fina_collections fc WHERE ".implode(' AND ',$where)." GROUP BY fc.currency_code ORDER BY fc.currency_code",$params);
$methods=dbFetchAll("SELECT fc.payment_method,COUNT(*) total_count,COALESCE(SUM(fc.amount),0) total_amount,SUM(fc.status='pending') pending_count,SUM(fc.status='approved') approved_count,SUM(fc.status='returned') returned_count FROM fina_collections fc WHERE ".implode(' AND ',$where)." GROUP BY fc.payment_method ORDER BY total_amount DESC",$params);
$sources=dbFetchAll("SELECT fs.source_type,COUNT(*) total_count,COALESCE(SUM(fc.amount),0) total_amount,SUM(fc.status='approved') approved_count,SUM(fc.status='returned') returned_count FROM fina_collections fc JOIN fina_sources fs ON fs.id=fc.fina_source_id WHERE ".implode(' AND ',$where)." GROUP BY fs.source_type ORDER BY total_amount DESC",$params);
$reviewed=dbFetchOne("SELECT COUNT(*) total_reviewed,SUM(status='approved') approved_count,SUM(status='returned') returned_count,COALESCE(SUM(CASE WHEN status='approved' THEN amount ELSE 0 END),0) approved_amount,COALESCE(SUM(CASE WHEN status='returned' THEN amount ELSE 0 END),0) returned_amount FROM fina_collections fc WHERE ".implode(' AND ',$where),$params);
$methodLabels=['cash'=>'نقدي','bank_transfer'=>'تحويل بنكي','credit_card'=>'بطاقة','mobile'=>'محفظة إلكترونية','other'=>'أخرى'];
$sourceLabels=['sponsor'=>'كفيل من أهل الخير','person'=>'شخص خارجي','organization'=>'منظمة / جهة','other'=>'أخرى'];
include dirname(__DIR__,2).'/includes/header.php';
?>
<style>@media print{.no-print,.sidebar,.qa-top-bar{display:none!important}.content,.main-content{margin:0!important;width:100%!important}.card{box-shadow:none!important;border:1px solid #ddd!important}}</style>
<div class="container-fluid py-4">
<div class="d-flex justify-content-between align-items-center mb-3 flex-wrap gap-2 no-print"><div><h2><i class="fas fa-file-chart-column me-2"></i>تقرير تحصيلات فينا الخير</h2><div class="text-muted">تقرير تحليلي مستقل لفترة محددة، وليس سجل معاملات تفصيلي.<?php if($supervisorOwnOnly):?> أنت ترى فقط التحصيلات التي سجلتها بنفسك.<?php endif;?></div></div><div class="d-flex gap-2"><a href="<?php echo APP_URL;?>modules/accounting/fina_payment_review.php" class="btn btn-outline-primary"><i class="fas fa-clipboard-check me-1"></i>المراجعة</a><a href="<?php echo APP_URL;?>modules/accounting/fina_payment_history.php" class="btn btn-outline-primary"><i class="fas fa-clock-rotate-left me-1"></i>السجل</a><button onclick="window.print()" class="btn btn-secondary"><i class="fas fa-print me-1"></i>طباعة</button></div></div>
<div class="card mb-3 no-print"><div class="card-body"><form class="row g-2 align-items-end"><div class="col-md-4"><label class="form-label">من تاريخ</label><input type="date" name="from" value="<?php echo e($from);?>" class="form-control"></div><div class="col-md-4"><label class="form-label">إلى تاريخ</label><input type="date" name="to" value="<?php echo e($to);?>" class="form-control"></div><div class="col-md-2"><label class="form-label">العملة</label><select name="currency" class="form-select"><option value="">كل العملات</option><?php foreach($currencies as $c):?><option value="<?php echo e($c['code']);?>" <?php echo $currency===$c['code']?'selected':'';?>><?php echo e($c['code']);?></option><?php endforeach;?></select></div><div class="col-md-2"><button class="btn btn-primary w-100"><i class="fas fa-filter me-1"></i>عرض التقرير</button></div></form></div></div>
<div class="alert alert-info"><strong>الفترة:</strong> <?php echo e($from);?> إلى <?php echo e($to);?> — <strong>إجمالي السجلات:</strong> <?php echo number_format((int)($reviewed['total_reviewed']??0));?></div>
<div class="row g-3 mb-4"><div class="col-12 col-xl-4"><div class="card h-100"><div class="card-header"><strong>حالة المراجعة</strong></div><div class="card-body"><div class="row g-3 text-center"><div class="col-4"><div class="text-muted small">المراجعة</div><div class="fs-5 fw-bold"><?php echo(int)($reviewed['total_reviewed']??0);?></div></div><div class="col-4"><div class="text-muted small">معتمد</div><div class="fs-5 fw-bold text-success"><?php echo(int)($reviewed['approved_count']??0);?></div><small><?php echo number_format((float)($reviewed['approved_amount']??0),2);?></small></div><div class="col-4"><div class="text-muted small">مرتجع</div><div class="fs-5 fw-bold text-danger"><?php echo(int)($reviewed['returned_count']??0);?></div><small><?php echo number_format((float)($reviewed['returned_amount']??0),2);?></small></div></div></div></div></div>
<?php foreach($summary as $s):?><div class="col-12 col-xl-4"><div class="card h-100"><div class="card-header"><strong>عملة <?php echo e($s['currency_code']);?></strong></div><div class="card-body"><div class="row g-2 text-center"><div class="col-6"><div class="text-muted small">إجمالي</div><div class="fs-5 fw-bold"><?php echo number_format((float)$s['total_amount'],2);?></div><small><?php echo(int)$s['total_count'];?> سجل</small></div><div class="col-6"><div class="text-muted small">معتمد</div><div class="fs-5 fw-bold text-success"><?php echo number_format((float)$s['approved_amount'],2);?></div><small><?php echo(int)$s['approved_count'];?> سجل</small></div><div class="col-6"><div class="text-muted small">معلق</div><div class="fw-bold text-warning"><?php echo number_format((float)$s['pending_amount'],2);?></div><small><?php echo(int)$s['pending_count'];?> سجل</small></div><div class="col-6"><div class="text-muted small">مرتجع</div><div class="fw-bold text-danger"><?php echo number_format((float)$s['returned_amount'],2);?></div><small><?php echo(int)$s['returned_count'];?> سجل</small></div></div></div></div></div><?php endforeach;?></div>
<div class="row g-3"><div class="col-12 col-xl-6"><div class="card"><div class="card-header"><strong>التوزيع حسب طريقة الدفع</strong></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-sm table-hover mb-0"><thead class="table-light"><tr><th>طريقة الدفع</th><th>السجلات</th><th>الإجمالي</th><th>معلق</th><th>معتمد</th><th>مرتجع</th></tr></thead><tbody><?php if(!$methods):?><tr><td colspan="6" class="text-center text-muted py-4">لا توجد بيانات.</td></tr><?php else:foreach($methods as $m):?><tr><td><?php echo e($methodLabels[$m['payment_method']]??$m['payment_method']);?></td><td><?php echo(int)$m['total_count'];?></td><td><?php echo number_format((float)$m['total_amount'],2);?></td><td><?php echo(int)$m['pending_count'];?></td><td><?php echo(int)$m['approved_count'];?></td><td><?php echo(int)$m['returned_count'];?></td></tr><?php endforeach;endif;?></tbody></table></div></div></div></div>
<div class="col-12 col-xl-6"><div class="card"><div class="card-header"><strong>التوزيع حسب مصدر الأموال</strong></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-sm table-hover mb-0"><thead class="table-light"><tr><th>المصدر</th><th>السجلات</th><th>الإجمالي</th><th>معتمد</th><th>مرتجع</th></tr></thead><tbody><?php if(!$sources):?><tr><td colspan="5" class="text-center text-muted py-4">لا توجد بيانات.</td></tr><?php else:foreach($sources as $s):?><tr><td><?php echo e($sourceLabels[$s['source_type']]??$s['source_type']);?></td><td><?php echo(int)$s['total_count'];?></td><td><?php echo number_format((float)$s['total_amount'],2);?></td><td><?php echo(int)$s['approved_count'];?></td><td><?php echo(int)$s['returned_count'];?></td></tr><?php endforeach;endif;?></tbody></table></div></div></div></div></div>
</div>
<?php include dirname(__DIR__,2).'/includes/footer.php';?>