<?php
// modules/accounting/fina_settlements.php - Settlement of protected funds payable to فينا الخير
require_once dirname(__DIR__,2).'/config/config.php';
require_once dirname(__DIR__,2).'/config/database.php';
require_once dirname(__DIR__,2).'/config/functions.php';
require_once dirname(__DIR__,2).'/config/session.php';
require_once __DIR__.'/lib.php';
require_once __DIR__.'/lib_fina.php';
Session::start();
if(!Session::isLoggedIn()){header('Location: '.APP_URL.'index.php');exit();}
$role=Session::getUserRole();$uid=(int)Session::getUserId();
if(!in_array($role,['financial_manager','accountant_staff','admin'],true)){header('Location: '.APP_URL.'index.php');exit();}
$pageTitle='تسويات أموال فينا الخير';$active='fm_review';ak_ensure_tables();ak_seed_accounts();
$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'&&verify_csrf()){
    $action=$_POST['action']??'';$sid=(int)($_POST['settlement_id']??0);
    try{
        db()->beginTransaction();
        if($action==='create'){
            if(!in_array($role,['accountant_staff','financial_manager','admin'],true))throw new RuntimeException('غير مصرح.');
            $amount=round((float)str_replace(',','',$_POST['amount']??0),2);$currency=trim($_POST['currency_code']??'SDG');$method=$_POST['transfer_method']??'bank_transfer';$destRef=trim($_POST['destination_reference']??'');$external=trim($_POST['external_reference']??'');
            if($amount<=0)throw new RuntimeException('مبلغ التسوية يجب أن يكون أكبر من صفر.');if(!in_array($method,['bank_transfer','cash','other'],true))throw new RuntimeException('طريقة التحويل غير صالحة.');
            $rows=dbFetchAll("SELECT id,fina_share_amount,settled_amount,currency_code FROM fina_payment_allocations WHERE status IN ('protected','partially_settled') AND currency_code=? ORDER BY id FOR UPDATE",[$currency]);$remaining=$amount;$links=[];
            foreach($rows as $r){$available=round((float)$r['fina_share_amount']-(float)$r['settled_amount'],2);if($available<=0)continue;$use=min($remaining,$available);if($use>0){$links[]=[(int)$r['id'],$use];$remaining=round($remaining-$use,2);}if($remaining<=0)break;}
            if($remaining>0)throw new RuntimeException('لا توجد أموال محمية كافية لتغطية مبلغ التسوية. لا يمكن استخدام أموال أهل الخير لتمويل تحويل فينا الخير.');
            $count=(int)(dbFetchOne("SELECT COUNT(*) c FROM fina_settlements")['c']??0)+1;$code='FINA-STL-'.date('Ym').'-'.str_pad((string)$count,5,'0','0');$integration='FINA-SETTLE-'.$code;
            dbExecute("INSERT INTO fina_settlements (settlement_code,settlement_date,amount,currency_code,transfer_method,destination_name,destination_reference,external_reference,status,created_by,integration_reference) VALUES (?,?,?,?,?,'فينا الخير',?,?, 'pending_approval',?,?,?)",[$code,date('Y-m-d'),$amount,$currency,$method,$destRef!==''?$destRef:null,$external!==''?$external:null,$uid,$integration]);$newId=(int)dbLastInsertId();
            foreach($links as $ln)dbExecute("INSERT INTO fina_settlement_allocations (settlement_id,allocation_id,amount) VALUES (?,?,?)",[$newId,$ln[0],$ln[1]]);
            db()->commit();flash('success','تم إنشاء طلب التسوية وإرساله للاعتماد.');
        }elseif($action==='approve'){
            if(!in_array($role,['financial_manager','admin'],true))throw new RuntimeException('اعتماد التسوية متاح للمدير المالي فقط.');
            $s=dbFetchOne("SELECT * FROM fina_settlements WHERE id=? AND status='pending_approval' FOR UPDATE",[$sid]);if(!$s)throw new RuntimeException('طلب التسوية غير موجود أو تمت معالجته.');
            dbExecute("UPDATE fina_settlements SET status='approved',reviewed_by=?,reviewed_at=NOW() WHERE id=? AND status='pending_approval'",[$uid,$sid]);
            if(db()->rowCount()!==1)throw new RuntimeException('تعذر اعتماد التسوية.');db()->commit();flash('success','تم اعتماد تسوية فينا الخير.');
        }elseif($action==='transfer'){
            if(!in_array($role,['financial_manager','admin'],true))throw new RuntimeException('تنفيذ التحويل متاح للمدير المالي فقط.');
            $s=dbFetchOne("SELECT * FROM fina_settlements WHERE id=? AND status='approved' FOR UPDATE",[$sid]);if(!$s)throw new RuntimeException('التسوية ليست جاهزة للتنفيذ.');
            $links=dbFetchAll("SELECT fsa.*,fpa.fina_share_amount,fpa.settled_amount,fpa.currency_code FROM fina_settlement_allocations fsa JOIN fina_payment_allocations fpa ON fpa.id=fsa.allocation_id WHERE fsa.settlement_id=? FOR UPDATE",[$sid]);$total=0.0;foreach($links as $ln){if($ln['currency_code']!==$s['currency_code'])throw new RuntimeException('عملة التسوية لا تطابق عملة الأموال المحمية.');$available=round((float)$ln['fina_share_amount']-(float)$ln['settled_amount'],2);if((float)$ln['amount']<=0||(float)$ln['amount']>$available)throw new RuntimeException('مبلغ أحد تخصيصات التسوية يتجاوز الرصيد المتاح لفينا الخير.');$total+=round((float)$ln['amount'],2);}if(round($total,2)!==(float)$s['amount'])throw new RuntimeException('مجموع تخصيصات التسوية لا يساوي مبلغ التسوية.');
            $cashCode=$s['transfer_method']==='bank_transfer'?'1200':($s['transfer_method']==='cash'?'1100':'1100');$cashId=ak_account_id($cashCode);$payableId=ak_account_id('2300');if($cashId<=0||$payableId<=0)throw new RuntimeException('حساب التسوية غير موجود.');
            $n=(int)(dbFetchOne("SELECT COALESCE(MAX(CASE WHEN entry_code REGEXP '^JE-[0-9]+$' THEN CAST(SUBSTRING(entry_code,4) AS UNSIGNED) ELSE 0 END),0) n FROM journal_entries")['n']??0)+1;$code='JE-'.str_pad((string)$n,6,'0','0');
            dbExecute("INSERT INTO journal_entries (entry_code,entry_date,description,reference_type,reference_id,status,created_by) VALUES (?,?,?,'fina_settlement',?,'posted',?)",[$code,$s['settlement_date'],'تسوية وتحويل أموال فينا الخير '.$s['settlement_code'],$sid,$uid]);$eid=(int)dbLastInsertId();dbExecute("INSERT INTO journal_lines (entry_id,account_id,debit,credit,description) VALUES (?,?,?,?,?)",[$eid,$payableId,$s['amount'],0,'تسوية مستحقات فينا الخير '.$s['settlement_code']]);dbExecute("INSERT INTO journal_lines (entry_id,account_id,debit,credit,description) VALUES (?,?,?,?,?)",[$eid,$cashId,0,$s['amount'],'تحويل أموال إلى فينا الخير '.$s['settlement_code']]);
            foreach($links as $ln){$newSettled=round((float)$ln['settled_amount']+(float)$ln['amount'],2);$newStatus=$newSettled>=(float)$ln['fina_share_amount']?'settled':'partially_settled';dbExecute("UPDATE fina_payment_allocations SET settled_amount=?,status=? WHERE id=?",[$newSettled,$newStatus,(int)$ln['allocation_id']]);}
            dbExecute("UPDATE fina_settlements SET status='transferred',journal_entry_id=? WHERE id=? AND status='approved'",[$eid,$sid]);if(db()->rowCount()!==1)throw new RuntimeException('تعذر تثبيت حالة التحويل.');db()->commit();flash('success','تم تنفيذ تسوية فينا الخير وتسجيل قيدها المحاسبي.');
        }elseif($action==='return'){
            if(!in_array($role,['financial_manager','admin'],true))throw new RuntimeException('إرجاع التسوية متاح للمدير المالي فقط.');$s=dbFetchOne("SELECT id FROM fina_settlements WHERE id=? AND status='pending_approval' FOR UPDATE",[$sid]);if(!$s)throw new RuntimeException('التسوية غير موجودة أو تمت معالجتها.');dbExecute("UPDATE fina_settlements SET status='returned',reviewed_by=?,reviewed_at=NOW(),review_note=? WHERE id=?",[$uid,trim($_POST['review_note']??'')?:'تم إرجاع طلب التسوية للمراجعة.',$sid]);db()->commit();flash('success','تم إرجاع طلب التسوية.');
        }else{throw new RuntimeException('إجراء غير معروف.');}
    }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();$errors[]=$e->getMessage();}
}
$pending=dbFetchAll("SELECT fs.*,u.full_name creator,r.full_name reviewer FROM fina_settlements fs LEFT JOIN users u ON u.id=fs.created_by LEFT JOIN users r ON r.id=fs.reviewed_by WHERE fs.status='pending_approval' ORDER BY fs.created_at ASC");
$approved=dbFetchAll("SELECT fs.*,u.full_name creator,r.full_name reviewer FROM fina_settlements fs LEFT JOIN users u ON u.id=fs.created_by LEFT JOIN users r ON r.id=fs.reviewed_by WHERE fs.status='approved' ORDER BY fs.created_at ASC");
$history=dbFetchAll("SELECT fs.*,je.entry_code FROM fina_settlements fs LEFT JOIN journal_entries je ON je.id=fs.journal_entry_id WHERE fs.status IN ('transferred','returned','cancelled','voided') ORDER BY fs.updated_at DESC LIMIT 50");
$balances=dbFetchAll("SELECT currency_code,ROUND(SUM(fina_share_amount-settled_amount),2) available FROM fina_payment_allocations WHERE status IN ('protected','partially_settled') GROUP BY currency_code HAVING available>0 ORDER BY currency_code");
include dirname(__DIR__,2).'/includes/header.php';
?>
<div class="welcome-section fade-in"><h2><i class="fas fa-building-columns me-2"></i>تسويات أموال فينا الخير</h2><p>هذه الصفحة تتعامل مع الأموال المحمية المستحقة لـ <strong>فينا الخير</strong>. التحويل ليس مصروفاً على أهل الخير؛ بل تسوية للالتزام.</p></div>
<?php include dirname(__DIR__,2).'/includes/alerts.php'; ?><?php if($errors):?><div class="alert alert-danger"><ul class="mb-0"><?php foreach($errors as $e):?><li><?php echo e($e);?></li><?php endforeach;?></ul></div><?php endif;?>
<div class="card mb-4"><div class="card-header">الرصيد المحمي المتاح للتحويل</div><div class="card-body"><div class="row g-2"><?php foreach($balances as $b):?><div class="col-md-3"><div class="border rounded p-3"><div class="text-muted small"><?php echo e($b['currency_code']);?></div><div class="fs-4 fw-bold"><?php echo number_format((float)$b['available'],2);?></div></div></div><?php endforeach;if(!$balances):?><div class="text-muted">لا يوجد رصيد محمي متاح حالياً.</div><?php endif;?></div></div></div>
<?php if(in_array($role,['accountant_staff','financial_manager','admin'],true)):?><div class="card mb-4"><div class="card-header">إنشاء طلب تسوية</div><div class="card-body"><form method="post" class="row g-3"><?php echo csrf_field();?><input type="hidden" name="action" value="create"><div class="col-md-3"><label class="form-label">المبلغ</label><input type="number" min="0.01" step="0.01" name="amount" class="form-control" required></div><div class="col-md-2"><label class="form-label">العملة</label><input name="currency_code" class="form-control" value="SDG" maxlength="3" required></div><div class="col-md-3"><label class="form-label">طريقة التحويل</label><select name="transfer_method" class="form-select"><option value="bank_transfer">تحويل بنكي</option><option value="cash">نقدي</option><option value="other">أخرى</option></select></div><div class="col-md-4"><label class="form-label">مرجع التحويل</label><input name="destination_reference" class="form-control"></div><div class="col-md-4"><label class="form-label">مرجع خارجي</label><input name="external_reference" class="form-control" dir="ltr"></div><div class="col-12"><button class="btn btn-primary">إنشاء طلب التسوية</button></div></form></div></div><?php endif;?>
<div class="card mb-4"><div class="card-header">طلبات بانتظار اعتماد المدير المالي</div><div class="card-body p-0"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>الرمز</th><th>المبلغ</th><th>الطريقة</th><th>المنشئ</th><th>الإجراء</th></tr></thead><tbody><?php if(!$pending):?><tr><td colspan="5" class="text-center text-muted py-3">لا توجد طلبات.</td></tr><?php else:foreach($pending as $s):?><tr><td><?php echo e($s['settlement_code']);?></td><td><?php echo number_format((float)$s['amount'],2).' '.e($s['currency_code']);?></td><td><?php echo e($s['transfer_method']);?></td><td><?php echo e($s['creator']??'—');?></td><td><?php if(in_array($role,['financial_manager','admin'],true)):?><form method="post" class="d-inline"><?php echo csrf_field();?><input type="hidden" name="action" value="approve"><input type="hidden" name="settlement_id" value="<?php echo (int)$s['id'];?>"><button class="btn btn-sm btn-success" onclick="return confirm('اعتماد طلب التسوية؟')">اعتماد</button></form><form method="post" class="d-inline"><?php echo csrf_field();?><input type="hidden" name="action" value="return"><input type="hidden" name="settlement_id" value="<?php echo (int)$s['id'];?>"><input type="hidden" name="review_note" value="يرجى مراجعة طلب التسوية."><button class="btn btn-sm btn-danger">إرجاع</button></form><?php else:?>بانتظار اعتماد المدير المالي<?php endif;?></td></tr><?php endforeach;endif;?></tbody></table></div></div></div>
<div class="card mb-4"><div class="card-header">تسويات معتمدة بانتظار التنفيذ</div><div class="card-body p-0"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>الرمز</th><th>المبلغ</th><th>المرجع</th><th>الإجراء</th></tr></thead><tbody><?php if(!$approved):?><tr><td colspan="4" class="text-center text-muted py-3">لا توجد تسويات جاهزة.</td></tr><?php else:foreach($approved as $s):?><tr><td><?php echo e($s['settlement_code']);?></td><td><?php echo number_format((float)$s['amount'],2).' '.e($s['currency_code']);?></td><td><?php echo e($s['destination_reference']??'—');?></td><td><?php if(in_array($role,['financial_manager','admin'],true)):?><form method="post"><?php echo csrf_field();?><input type="hidden" name="action" value="transfer"><input type="hidden" name="settlement_id" value="<?php echo (int)$s['id'];?>"><button class="btn btn-sm btn-primary" onclick="return confirm('تنفيذ تحويل أموال فينا الخير وتسجيل القيد؟')">تنفيذ التحويل وتسجيل القيد</button></form><?php endif;?></td></tr><?php endforeach;endif;?></tbody></table></div></div></div>
<div class="card"><div class="card-header">السجل</div><div class="card-body p-0"><div class="table-responsive"><table class="table table-sm"><thead><tr><th>الرمز</th><th>المبلغ</th><th>الحالة</th><th>القيد</th><th>التاريخ</th></tr></thead><tbody><?php foreach($history as $s):?><tr><td><?php echo e($s['settlement_code']);?></td><td><?php echo number_format((float)$s['amount'],2).' '.e($s['currency_code']);?></td><td><?php echo e($s['status']);?></td><td><?php echo e($s['entry_code']??'—');?></td><td><?php echo e($s['updated_at']);?></td></tr><?php endforeach;?></tbody></table></div></div></div>
<?php include dirname(__DIR__,2).'/includes/footer.php'; ?>
