<?php
require_once dirname(__DIR__,2).'/config/config.php';
require_once dirname(__DIR__,2).'/config/database.php';
require_once dirname(__DIR__,2).'/config/functions.php';
require_once dirname(__DIR__,2).'/config/session.php';
require_once __DIR__.'/fina_lib.php';
Session::start();
if(!Session::isLoggedIn()){header('Location: '.APP_URL.'index.php');exit();}
$role=Session::getUserRole();
if(!in_array($role,['financial_manager','fm','supervisor','admin','vice_general_manager'],true)){header('Location: '.APP_URL.'index.php');exit();}
fina_ensure_tables();
$pageTitle='تقرير تحصيلات فينا الخير';
$active='fina_report';
$from=trim($_GET['from']??date('Y-m-01'));$to=trim($_GET['to']??date('Y-m-d'));$currency=trim($_GET['currency']??'');
$validFrom=preg_match('/^\d{4}-\d{2}-\d{2}$/',$from);$validTo=preg_match('/^\d{4}-\d{2}-\d{2}$/',$to);if(!$validFrom)$from=date('Y-m-01');if(!$validTo)$to=date('Y-m-d');
$currencies=dbFetchAll("SELECT code FROM currencies ORDER BY code");
$where=['fc.collection_date BETWEEN ? AND ?'];$params=[$from,$to];if($currency!==''){$where[]='fc.currency_code=?';$params[]=$currency;}
$summary=dbFetchAll("SELECT fc.currency_code,COUNT(*) total_count,COALESCE(SUM(fc.amount),0) total_amount,SUM(fc.status='pending') pending_count,COALESCE(SUM(CASE WHEN fc.status='pending' THEN fc.amount ELSE 0 END),0) pending_amount,SUM(fc.status='approved') approved_count,COALESCE(SUM(CASE WHEN fc.status='approved' THEN fc.amount ELSE 0 END),0) approved_amount,SUM(fc.status='returned') returned_count,COALESCE(SUM(CASE WHEN fc.status='returned' THEN fc.amount ELSE 0 END),0) returned_amount FROM fina_collections fc WHERE ".implode(' AND ',$where)." GROUP BY fc.currency_code ORDER BY fc.currency_code",$params);
$rows=dbFetchAll("SELECT fc.id,fc.collection_date,fc.amount,fc.currency_code,fc.payment_method,fc.status,fc.accounting_journal_id,fs.source_type,fs.source_name,s.full_name sponsor_name,s.sponsor_code,cu.full_name creator_name,ru.full_name reviewer_name FROM fina_collections fc JOIN fina_sources fs ON fs.id=fc.fina_source_id LEFT JOIN sponsors s ON s.id=fs.sponsor_id JOIN users cu ON cu.id=fc.created_by LEFT JOIN users ru ON ru.id=fc.reviewed_by WHERE ".implode(' AND ',$where)." ORDER BY fc.collection_date DESC,fc.id DESC",$params);
$methodLabels=['cash'=>'نقدي','bank_transfer'=>'تحويل بنكي','credit_card'=>'بطاقة','mobile'=>'محفظة إلكترونية','other'=>'أخرى'];
include dirname(__DIR__,2).'/includes/header.php';
?>
<style>@media print{.no-print,.sidebar,.qa-top-bar{display:none!important}.content,.main-content{margin:0!important;width:100%!important}.card{box-shadow:none!important;border:1px solid #ddd!important}}</style>
<div class="container-fluid py-4">
<div class="d-flex justify-content-between align-items-center mb-3 flex-wrap gap-2 no-print"><div><h2><i class="fas fa-file-chart-column me-2"></i>تقرير تحصيلات فينا الخير</h2><div class="text-muted">تقرير مستقل للأموال المخصصة 100% لفينا الخير.</div></div><div class="d-flex gap-2"><a href="<?php echo APP_URL;?>modules/accounting/fina_payment_history.php" class="btn btn-outline-primary"><i class="fas fa-clock-rotate-left me-1"></i>السجل</a><button onclick="window.print()" class="btn btn-secondary"><i class="fas fa-print me-1"></i>طباعة</button></div></div>
<div class="card mb-3 no-print"><div class="card-body"><form class="row g-2 align-items-end"><div class="col-md-4"><label class="form-label">من تاريخ</label><input type="date" name="from" value="<?php echo e($from);?>" class="form-control"></div><div class="col-md-4"><label class="form-label">إلى تاريخ</label><input type="date" name="to" value="<?php echo e($to);?>" class="form-control"></div><div class="col-md-2"><label class="form-label">العملة</label><select name="currency" class="form-select"><option value="">كل العملات</option><?php foreach($currencies as $c):?><option value="<?php echo e($c['code']);?>" <?php echo $currency===$c['code']?'selected':'';?>><?php echo e($c['code']);?></option><?php endforeach;?></select></div><div class="col-md-2"><button class="btn btn-primary w-100"><i class="fas fa-filter me-1"></i>عرض التقرير</button></div></form></div></div>
<div class="alert alert-info"><strong>الفترة:</strong> <?php echo e($from);?> إلى <?php echo e($to);?> — <strong>عدد السجلات:</strong> <?php echo count($rows);?></div>
<div class="row g-3 mb-4"><?php if(!$summary):?><div class="col-12"><div class="card"><div class="card-body text-center text-muted">لا توجد تحصيلات في الفترة المحددة.</div></div></div><?php else:foreach($summary as $s):?><div class="col-12 col-xl-4"><div class="card h-100"><div class="card-header"><strong>عملة <?php echo e($s['currency_code']);?></strong></div><div class="card-body"><div class="row g-2 text-center"><div class="col-6"><div class="text-muted small">إجمالي التحصيل</div><div class="fs-5 fw-bold"><?php echo number_format((float)$s['total_amount'],2);?></div><small><?php echo(int)$s['total_count'];?> سجل</small></div><div class="col-6"><div class="text-muted small">معتمد</div><div class="fs-5 fw-bold text-success"><?php echo number_format((float)$s['approved_amount'],2);?></div><small><?php echo(int)$s['approved_count'];?> سجل</small></div><div class="col-6"><div class="text-muted small">بانتظار المراجعة</div><div class="fw-bold text-warning"><?php echo number_format((float)$s['pending_amount'],2);?></div><small><?php echo(int)$s['pending_count'];?> سجل</small></div><div class="col-6"><div class="text-muted small">مرتجع</div><div class="fw-bold text-danger"><?php echo number_format((float)$s['returned_amount'],2);?></div><small><?php echo(int)$s['returned_count'];?> سجل</small></div></div></div></div></div><?php endforeach;endif;?></div>
<div class="card"><div class="card-header"><strong>تفاصيل التقرير</strong></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-sm table-hover align-middle mb-0"><thead class="table-light"><tr><th>#</th><th>التاريخ</th><th>المصدر</th><th>المبلغ</th><th>طريقة الدفع</th><th>الحالة</th><th>المنشئ</th><th>المراجع</th><th>القيد</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="9" class="text-center text-muted py-4">لا توجد بيانات.</td></tr><?php else:foreach($rows as $r):$source=$r['source_type']==='sponsor'?'كفيل — '.($r['sponsor_code']??'').' — '.($r['sponsor_name']??''):(['person'=>'شخص خارجي','organization'=>'منظمة / جهة','other'=>'أخرى'][$r['source_type']]??'أخرى').' — '.($r['source_name']??'');?><tr><td><?php echo(int)$r['id'];?></td><td><?php echo e($r['collection_date']);?></td><td><?php echo e($source);?></td><td><strong><?php echo number_format((float)$r['amount'],2);?></strong> <?php echo e($r['currency_code']);?></td><td><?php echo e($methodLabels[$r['payment_method']]??$r['payment_method']);?></td><td><?php echo $r['status']==='approved'?'<span class="badge bg-success">معتمد</span>':($r['status']==='returned'?'<span class="badge bg-danger">مرتجع</span>':'<span class="badge bg-warning text-dark">بانتظار المراجعة</span>');?></td><td><?php echo e($r['creator_name']);?></td><td><?php echo e($r['reviewer_name']??'—');?></td><td><?php echo $r['accounting_journal_id']?'<span class="badge bg-primary">JE #'.(int)$r['accounting_journal_id'].'</span>':'—';?></td></tr><?php endforeach;endif;?></tbody></table></div></div></div>
</div>
<?php include dirname(__DIR__,2).'/includes/footer.php';?>