<?php
require_once dirname(__DIR__, 2) . '/config/config.php';
require_once dirname(__DIR__, 2) . '/config/database.php';
require_once dirname(__DIR__, 2) . '/config/functions.php';
require_once dirname(__DIR__, 2) . '/config/session.php';
require_once __DIR__ . '/fina_settlement_lib.php';
Session::start();
$role = (string) Session::getUserRole();
if (!Session::isLoggedIn() || $role !== 'financial_manager') { http_response_code(403); include dirname(__DIR__, 2) . '/includes/header.php'; echo '<div class="container py-5"><div class="alert alert-danger"><i class="fas fa-lock me-1"></i>تسويات فينا الخير متاحة للمدير المالي فقط.</div></div>'; exit; }
fina_settlement_ensure_tables();
$pageTitle = 'تسويات فينا الخير'; $active = 'fina_settlements'; $uid = (int) Session::getUserId();
function fina_settlement_status_label(string $status): string { $labels=['draft'=>'<span class="badge bg-secondary">مسودة</span>','approved'=>'<span class="badge bg-warning text-dark">معتمدة للتحويل</span>','transferred'=>'<span class="badge bg-primary">تم التحويل</span>','reconciled'=>'<span class="badge bg-info text-dark">تمت المطابقة</span>','closed'=>'<span class="badge bg-success">مغلقة</span>','cancelled'=>'<span class="badge bg-danger">ملغاة</span>']; return $labels[$status] ?? e($status); }
function fina_settlement_payment_label(string $method): string { return ['cash'=>'نقدي','bank_transfer'=>'تحويل بنكي','credit_card'=>'بطاقة','mobile'=>'محفظة إلكترونية','other'=>'أخرى'][$method] ?? $method; }
function fina_settlement_upload_evidence(): ?string { if(!isset($_FILES['evidence']) || ($_FILES['evidence']['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)return null; if($_FILES['evidence']['error']!==UPLOAD_ERR_OK)throw new RuntimeException('تعذر رفع مستند إثبات التحويل.'); if((int)$_FILES['evidence']['size']>5*1024*1024)throw new RuntimeException('حجم مستند إثبات التحويل يجب ألا يتجاوز 5 ميجابايت.'); $ext=strtolower(pathinfo((string)$_FILES['evidence']['name'],PATHINFO_EXTENSION)); if(!in_array($ext,['pdf','jpg','jpeg','png'],true))throw new RuntimeException('صيغة إثبات التحويل يجب أن تكون PDF أو JPG أو JPEG أو PNG.'); $dir=dirname(__DIR__,2).'/storage/receipts/fina_settlements'; if(!is_dir($dir)&&!mkdir($dir,0755,true)&&!is_dir($dir))throw new RuntimeException('تعذر إنشاء مجلد مستندات تسويات فينا الخير.'); $safe='fina_settlement_'.date('YmdHis').'_'.bin2hex(random_bytes(8)).'.'.$ext; if(!move_uploaded_file($_FILES['evidence']['tmp_name'],$dir.'/'.$safe))throw new RuntimeException('تعذر حفظ مستند إثبات التحويل.'); return 'storage/receipts/fina_settlements/'.$safe; }
if($_SERVER['REQUEST_METHOD']==='POST'&&verify_csrf()){
 try{
  if(isset($_POST['create_settlement'])){ $id=fina_settlement_create_draft(['settlement_date'=>(string)($_POST['settlement_date']??''),'amount'=>(float)($_POST['amount']??0),'currency_code'=>APP_CURRENCY_CODE,'payment_method'=>(string)($_POST['payment_method']??'')],$uid); flash('success','تم إنشاء مسودة التسوية الكاملة لدورة فينا الخير.'); header('Location: '.APP_URL.'modules/accounting/fina_settlements.php?view='.$id); exit; }
  if(isset($_POST['approve_settlement'])){ fina_settlement_approve((int)$_POST['approve_settlement'],$uid); flash('success','تم اعتماد دورة التسوية الكاملة.'); }
  elseif(isset($_POST['transfer_settlement'])){ $evidence=fina_settlement_upload_evidence(); try{$journalId=fina_settlement_transfer((int)$_POST['transfer_settlement'],(string)($_POST['transfer_reference']??''),$evidence,(string)($_POST['actual_date']??''),$uid); flash('success','تم تسجيل التحويل الكامل وترحيل قيد التسوية رقم #'.$journalId.'.');}catch(Throwable $e){if($evidence){$absolute=dirname(__DIR__,2).'/'.$evidence;if(is_file($absolute))@unlink($absolute);}throw $e;} }
  elseif(isset($_POST['reconcile_settlement'])){ fina_settlement_mark_reconciled((int)$_POST['reconcile_settlement'],(string)($_POST['reconciliation_note']??''),$uid); flash('success','تمت مطابقة دورة التسوية.'); }
  elseif(isset($_POST['close_settlement'])){ fina_settlement_close((int)$_POST['close_settlement'],$uid); flash('success','تم إغلاق دورة التسوية. أصبح الحساب 2300 متاحاً لدورة Fina التالية.'); }
  elseif(isset($_POST['cancel_settlement'])){ fina_settlement_cancel((int)$_POST['cancel_settlement'],(string)($_POST['cancellation_note']??''),$uid); flash('success','تم إلغاء مسودة/تسوية فينا الخير.'); }
 }catch(Throwable $e){flash('error',$e->getMessage());}
 $redirect=APP_URL.'modules/accounting/fina_settlements.php'; if(!empty($_POST['settlement_id']))$redirect.='?view='.(int)$_POST['settlement_id']; header('Location: '.$redirect); exit;
}
$approvedTotal=(float)(dbFetchOne("SELECT COALESCE(SUM(amount),0) total FROM fina_collections WHERE status='approved' AND currency_code=?",[APP_CURRENCY_CODE])['total']??0);
$outstanding=fina_settlement_production_outstanding();
$activeCycle=dbFetchOne("SELECT id,settlement_code,amount,status FROM fina_settlements WHERE is_test=0 AND status IN ('draft','approved') ORDER BY id DESC LIMIT 1");
$settlements=dbFetchAll("SELECT s.*,u.full_name creator_name FROM fina_settlements s LEFT JOIN users u ON u.id=s.created_by ORDER BY s.id DESC LIMIT 100");
$viewId=(int)($_GET['view']??0); $view=null; $viewAllocations=[];
if($viewId>0){ $view=dbFetchOne("SELECT s.*,u.full_name creator_name,au.full_name approver_name,tu.full_name transferor_name,ru.full_name reconciler_name,cu.full_name canceller_name FROM fina_settlements s LEFT JOIN users u ON u.id=s.created_by LEFT JOIN users au ON au.id=s.approved_by LEFT JOIN users tu ON tu.id=s.transferred_by LEFT JOIN users ru ON ru.id=s.reconciled_by LEFT JOIN users cu ON cu.id=s.cancelled_by WHERE s.id=? LIMIT 1",[$viewId]); if($view)$viewAllocations=dbFetchAll("SELECT a.fina_collection_id,a.allocated_amount,c.amount,c.currency_code,c.collection_date,c.status,c.payment_method,fs.source_name,s.full_name sponsor_name,s.sponsor_code FROM fina_settlement_allocations a JOIN fina_collections c ON c.id=a.fina_collection_id JOIN fina_sources fs ON fs.id=c.fina_source_id LEFT JOIN sponsors s ON s.id=fs.sponsor_id WHERE a.settlement_id=? ORDER BY a.id",[$viewId]); }
include dirname(__DIR__,2).'/includes/header.php'; ?>
<div class="container-fluid py-4">
<div class="d-flex justify-content-between align-items-center mb-3 flex-wrap gap-2"><div><h2><i class="fas fa-building-columns me-2"></i>تسويات فينا الخير</h2><p class="text-muted mb-0">دورة تسوية كاملة للالتزام 2300 — المدير المالي فقط.</p></div><a href="<?php echo APP_URL; ?>modules/accounting/fm_dashboard.php" class="btn btn-outline-secondary"><i class="fas fa-arrow-right me-1"></i>العودة إلى لوحة المدير المالي</a></div>
<?php include dirname(__DIR__,2).'/includes/alerts.php'; ?>
<div class="alert alert-info border mb-4"><strong><i class="fas fa-circle-info me-1"></i>قاعدة الدورة:</strong> كل أموال Fina المستحقة حالياً تتجمع في <strong>2300</strong>. عند طلب التسوية يتم تحويل <strong>الرصيد الكامل فقط</strong> من حساب أموال Fina المحتفظ بها، ثم يعود 2300 إلى <strong>صفر</strong>. لا توجد تسوية جزئية ولا حساب تحويل من خزينة أهل الخير.</div>
<div class="row g-3 mb-4">
<div class="col-md-4"><div class="card border-warning h-100"><div class="card-body"><div class="text-muted">إجمالي التحصيلات المعتمدة</div><div class="fs-3 fw-bold"><?php echo number_format($approvedTotal,2); ?> <?php echo e(APP_CURRENCY_CODE); ?></div><div class="small text-muted">يشمل التحصيلات التاريخية المعتمدة.</div></div></div></div>
<div class="col-md-4"><div class="card border-primary h-100"><div class="card-body"><div class="text-muted">الرصيد المستحق لدورة التسوية الحالية</div><div class="fs-3 fw-bold"><?php echo number_format($outstanding,2); ?> <?php echo e(APP_CURRENCY_CODE); ?></div><div class="small text-muted">هذا هو المبلغ الكامل المطلوب لتصفير 2300.</div></div></div></div>
<div class="col-md-4"><div class="card border-success h-100"><div class="card-body"><div class="text-muted">حساب الالتزام</div><div class="fs-5 fw-bold">2300 — التزام مستحق لفينا الخير</div><div class="small text-muted">حساب دائم لا يُحذف؛ يعود إلى صفر بعد كل دورة كاملة.</div></div></div></div></div>
<?php if($view): ?>
<div class="card mb-4"><div class="card-header d-flex justify-content-between align-items-center"><strong>تفاصيل <?php echo e($view['settlement_code']); ?></strong><?php echo fina_settlement_status_label($view['status']); ?></div><div class="card-body">
<div class="row g-3 mb-3"><div class="col-md-3"><span class="text-muted d-block">المبلغ الكامل</span><strong><?php echo number_format((float)$view['amount'],2); ?> <?php echo e($view['currency_code']); ?></strong></div><div class="col-md-3"><span class="text-muted d-block">التاريخ</span><strong><?php echo e($view['settlement_date']); ?></strong></div><div class="col-md-3"><span class="text-muted d-block">طريقة التحويل</span><strong><?php echo e(fina_settlement_payment_label($view['payment_method'])); ?></strong></div><div class="col-md-3"><span class="text-muted d-block">حساب التسوية</span><strong>أموال فينا الخير المحتفظ بها</strong></div></div>
<?php if($view['transfer_reference']): ?><div class="alert alert-light border"><strong>مرجع التحويل:</strong> <?php echo e($view['transfer_reference']); ?><?php if($view['settlement_journal_id']): ?> — <strong>قيد التسوية:</strong> #<?php echo (int)$view['settlement_journal_id']; ?><?php endif; ?></div><?php endif; ?>
<h5>التحصيلات الداخلة في الدورة</h5><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>#</th><th>المصدر</th><th>التاريخ</th><th>المبلغ</th><th>المخصص الكامل</th></tr></thead><tbody><?php foreach($viewAllocations as $a): ?><tr><td><?php echo (int)$a['fina_collection_id']; ?></td><td><?php echo e($a['sponsor_name']?:$a['source_name']?:'—'); ?></td><td><?php echo e($a['collection_date']); ?></td><td><?php echo number_format((float)$a['amount'],2); ?> <?php echo e($a['currency_code']); ?></td><td><strong><?php echo number_format((float)$a['allocated_amount'],2); ?></strong></td></tr><?php endforeach; ?></tbody></table></div>
<div class="d-flex flex-wrap gap-2 mt-3">
<?php if($view['status']==='draft'): ?><form method="post"><?php echo csrf_field(); ?><input type="hidden" name="settlement_id" value="<?php echo $viewId; ?>"><button name="approve_settlement" value="<?php echo $viewId; ?>" class="btn btn-success" onclick="return confirm('اعتماد دورة التسوية الكاملة؟');"><i class="fas fa-check me-1"></i>اعتماد الدورة</button></form><button class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#cancelModal"><i class="fas fa-ban me-1"></i>إلغاء</button>
<?php elseif($view['status']==='approved'): ?><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#transferModal"><i class="fas fa-money-bill-transfer me-1"></i>تسجيل التحويل الكامل</button><button class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#cancelModal"><i class="fas fa-ban me-1"></i>إلغاء</button>
<?php elseif($view['status']==='transferred'): ?><button class="btn btn-info" data-bs-toggle="modal" data-bs-target="#reconcileModal"><i class="fas fa-scale-balanced me-1"></i>مطابقة</button>
<?php elseif($view['status']==='reconciled'): ?><form method="post"><?php echo csrf_field(); ?><input type="hidden" name="settlement_id" value="<?php echo $viewId; ?>"><button name="close_settlement" value="<?php echo $viewId; ?>" class="btn btn-success" onclick="return confirm('إغلاق دورة التسوية بعد اكتمال المطابقة؟');"><i class="fas fa-lock me-1"></i>إغلاق الدورة</button></form><?php endif; ?>
<?php if($view['evidence_path']): ?><a class="btn btn-outline-primary" target="_blank" rel="noopener" href="<?php echo APP_URL; ?>modules/accounting/fina_settlement_evidence.php?id=<?php echo $viewId; ?>"><i class="fas fa-paperclip me-1"></i>إثبات التحويل</a><?php endif; ?></div>
<?php if($view['status']==='closed'): ?><div class="alert alert-success mt-3 mb-0"><i class="fas fa-circle-check me-1"></i>اكتملت دورة التسوية. يجب أن يكون رصيد 2300 لهذه الدورة صفراً، مع بقاء الحساب نفسه للدورة التالية.</div><?php endif; ?>
</div></div>
<?php elseif($viewId>0): ?><div class="alert alert-warning">سجل التسوية المطلوب غير موجود.</div><?php endif; ?>
<div class="card mb-4"><div class="card-header"><strong>إنشاء دورة تسوية كاملة</strong></div><div class="card-body">
<?php if($activeCycle): ?><div class="alert alert-warning mb-0">توجد دورة نشطة بالفعل: <strong><?php echo e($activeCycle['settlement_code']); ?></strong> بمبلغ <?php echo number_format((float)$activeCycle['amount'],2); ?> <?php echo e(APP_CURRENCY_CODE); ?>. أكملها قبل إنشاء دورة أخرى.</div>
<?php elseif($outstanding<=0): ?><div class="alert alert-success mb-0">لا يوجد حالياً رصيد مستحق لتسوية فينا الخير. سيبدأ رصيد جديد في 2300 تلقائياً عند اعتماد تحصيل Fina جديد.</div>
<?php else: ?><form method="post"><?php echo csrf_field(); ?><input type="hidden" name="create_settlement" value="1"><div class="row g-3"><div class="col-md-4"><label class="form-label">تاريخ إنشاء الدورة</label><input type="date" name="settlement_date" class="form-control" value="<?php echo date('Y-m-d'); ?>" required></div><div class="col-md-4"><label class="form-label">المبلغ الكامل</label><input type="number" name="amount" class="form-control" value="<?php echo e(number_format($outstanding,2,'.','')); ?>" step="0.01" readonly><div class="form-text">يتم تحديده من كامل الرصيد المستحق ولا يمكن تقليله.</div></div><div class="col-md-4"><label class="form-label">طريقة التحويل إلى Fina</label><select name="payment_method" class="form-select" required><option value="">اختر</option><option value="bank_transfer">تحويل بنكي</option><option value="cash">نقدي</option><option value="mobile">محفظة إلكترونية</option><option value="credit_card">بطاقة</option><option value="other">أخرى</option></select></div></div><div class="alert alert-light border mt-3 mb-3"><strong>لا يوجد اختيار لحساب خزينة أهل الخير.</strong> محاسبة التسوية ستكون: <strong>مدين 2300 / دائن أموال فينا الخير المحتفظ بها</strong>.</div><button class="btn btn-primary" type="submit"><i class="fas fa-file-circle-plus me-1"></i>إنشاء دورة التسوية الكاملة</button></form><?php endif; ?></div></div>
<div class="card"><div class="card-header"><strong>سجل تسويات فينا الخير</strong></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>المرجع</th><th>التاريخ</th><th>المبلغ</th><th>النوع</th><th>الحالة</th><th>مرجع التحويل</th><th></th></tr></thead><tbody><?php if(!$settlements): ?><tr><td colspan="7" class="text-center text-muted py-4">لا توجد تسويات مسجلة بعد.</td></tr><?php else: foreach($settlements as $s): ?><tr><td><strong><?php echo e($s['settlement_code']); ?></strong></td><td><?php echo e($s['settlement_date']); ?></td><td><?php echo number_format((float)$s['amount'],2); ?> <?php echo e($s['currency_code']); ?></td><td><?php echo (int)$s['is_test']===1?'<span class="badge bg-secondary">اختبار تاريخي</span>':'<span class="badge bg-primary">دورة إنتاجية</span>'; ?></td><td><?php echo fina_settlement_status_label($s['status']); ?></td><td><?php echo e($s['transfer_reference']?:'—'); ?></td><td><a class="btn btn-sm btn-outline-primary" href="<?php echo APP_URL; ?>modules/accounting/fina_settlements.php?view=<?php echo (int)$s['id']; ?>">عرض</a></td></tr><?php endforeach; endif; ?></tbody></table></div></div></div>
</div>
<?php if($view&&$view['status']==='approved'): ?><div class="modal fade" id="transferModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="post" enctype="multipart/form-data"><?php echo csrf_field(); ?><div class="modal-header"><h5 class="modal-title">تسجيل التحويل الكامل إلى Fina</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="transfer_settlement" value="<?php echo $viewId; ?>"><input type="hidden" name="settlement_id" value="<?php echo $viewId; ?>"><div class="mb-3"><label class="form-label">تاريخ التحويل الفعلي</label><input type="date" name="actual_date" class="form-control" value="<?php echo date('Y-m-d'); ?>" required></div><div class="mb-3"><label class="form-label">مرجع التحويل</label><input type="text" name="transfer_reference" class="form-control" maxlength="150" required></div><div class="mb-3"><label class="form-label">إثبات التحويل</label><input type="file" name="evidence" class="form-control" accept=".pdf,.jpg,.jpeg,.png"><div class="form-text">اختياري — PDF/JPG/PNG حتى 5MB.</div></div><div class="alert alert-warning mb-0">سيتم ترحيل <strong>مدين 2300 / دائن أموال فينا الخير المحتفظ بها</strong> بكامل مبلغ الدورة.</div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">إلغاء</button><button class="btn btn-primary" type="submit"><i class="fas fa-money-bill-transfer me-1"></i>تسجيل التحويل الكامل</button></div></form></div></div></div><?php endif; ?>
<?php if($view&&in_array($view['status'],['draft','approved'],true)): ?><div class="modal fade" id="cancelModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="post"><?php echo csrf_field(); ?><div class="modal-header"><h5 class="modal-title">إلغاء دورة التسوية</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="cancel_settlement" value="<?php echo $viewId; ?>"><input type="hidden" name="settlement_id" value="<?php echo $viewId; ?>"><label class="form-label">سبب الإلغاء</label><textarea name="cancellation_note" class="form-control" rows="4" required></textarea></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">إلغاء</button><button class="btn btn-danger" type="submit">تأكيد الإلغاء</button></div></form></div></div></div><?php endif; ?>
<?php if($view&&$view['status']==='transferred'): ?><div class="modal fade" id="reconcileModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="post"><?php echo csrf_field(); ?><div class="modal-header"><h5 class="modal-title">مطابقة دورة التسوية</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="reconcile_settlement" value="<?php echo $viewId; ?>"><input type="hidden" name="settlement_id" value="<?php echo $viewId; ?>"><label class="form-label">ملاحظة المطابقة</label><textarea name="reconciliation_note" class="form-control" rows="4"></textarea></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">إلغاء</button><button class="btn btn-info" type="submit">تأكيد المطابقة</button></div></form></div></div></div><?php endif; ?>
<?php include dirname(__DIR__,2).'/includes/footer.php'; ?>
