<?php
// modules/reports/operational.php - Operational Reports
require_once dirname(__DIR__, 2) . '/config/config.php';
require_once dirname(__DIR__, 2) . '/config/database.php';
require_once dirname(__DIR__, 2) . '/config/functions.php';
require_once dirname(__DIR__, 2) . '/config/session.php';
Session::start();
if (!Session::isLoggedIn()) { header('Location: ' . APP_URL . 'index.php'); exit(); }
$role = Session::getUserRole();
$allowed_roles = ['admin','general_manager','vice_general_manager','supervisor','nanny','financial_manager'];
if (!in_array($role, $allowed_roles, true)) {
    $_SESSION['flash'][] = ['type'=>'error','message'=>t('operational.permission_denied')];
    header('Location: ' . APP_URL . 'modules/reports/index.php'); exit();
}
$from = trim($_GET['from'] ?? date('Y-m-01'));
$to = trim($_GET['to'] ?? date('Y-m-d'));
$report_type = trim($_GET['report'] ?? 'supervisor');
$pageTitle = t('operational.report_title');
$active = 'reports';

$supervisor_data=[];
if ($report_type==='supervisor') {
    $sql="SELECT u.id supervisor_id,u.full_name,COUNT(DISTINCT s.id) total_sponsors,SUM(CASE WHEN s.status='active' THEN 1 ELSE 0 END) active_sponsors,COALESCE(SUM(CASE WHEN t.status='posted' THEN t.amount ELSE 0 END),0) total_collected,COUNT(DISTINCT CASE WHEN t.status='posted' THEN t.id END) transaction_count FROM users u LEFT JOIN sponsors s ON s.supervisor_id=u.id LEFT JOIN transactions t ON t.sponsor_id=s.id AND t.transaction_date BETWEEN '{$from}' AND '{$to}' WHERE u.role_id=4 GROUP BY u.id,u.full_name ORDER BY total_collected DESC";
    $supervisor_data=dbFetchAll($sql);
    $total_supervisors=(int)(dbFetchOne("SELECT COUNT(*) c FROM users WHERE role_id=4")['c']??0);
    $total_sponsors_all=(int)(dbFetchOne("SELECT COUNT(*) c FROM sponsors")['c']??0);
    $active_sponsors_all=(int)(dbFetchOne("SELECT COUNT(*) c FROM sponsors WHERE status='active'")['c']??0);
}
$nanny_data=[];
if ($report_type==='nanny') {
    $sql="SELECT u.id nanny_id,u.full_name,COUNT(DISTINCT md.id) disbursement_count,COALESCE(SUM(md.total_amount),0) total_amount,SUM(CASE WHEN di.status='paid' THEN 1 ELSE 0 END) paid_families,SUM(CASE WHEN di.status='returned' THEN 1 ELSE 0 END) returned_families,SUM(CASE WHEN di.status='pending' THEN 1 ELSE 0 END) pending_families,COALESCE(SUM(CASE WHEN di.status='returned' THEN di.amount ELSE 0 END),0) returned_amount FROM users u LEFT JOIN monthly_disbursements md ON md.nanny_id=u.id AND md.month BETWEEN SUBSTRING('{$from}',1,7) AND SUBSTRING('{$to}',1,7) LEFT JOIN disbursement_items di ON di.disbursement_id=md.id WHERE u.role_id=7 GROUP BY u.id,u.full_name ORDER BY total_amount DESC";
    $nanny_data=dbFetchAll($sql);
    $total_nannies=(int)(dbFetchOne("SELECT COUNT(*) c FROM users WHERE role_id=7")['c']??0);
}
$verification_data=[];
if ($report_type==='verification') {
    $verification_data['summary']=dbFetchOne("SELECT COUNT(*) total_verifications,SUM(is_orphan_verified) orphan_verified,SUM(is_mother_contact_verified) mother_verified,SUM(is_bank_verified) bank_verified,SUM(CASE WHEN is_orphan_verified=1 AND is_mother_contact_verified=1 AND is_bank_verified=1 THEN 1 ELSE 0 END) fully_verified FROM nanny_family_verifications WHERE created_at BETWEEN '{$from}' AND '{$to}'");
    $verification_data['by_nanny']=dbFetchAll("SELECT u.full_name nanny_name,COUNT(nfv.id) total_families,SUM(nfv.is_orphan_verified) orphan_verified,SUM(nfv.is_mother_contact_verified) mother_verified,SUM(nfv.is_bank_verified) bank_verified,SUM(CASE WHEN nfv.is_orphan_verified=1 AND nfv.is_mother_contact_verified=1 AND nfv.is_bank_verified=1 THEN 1 ELSE 0 END) fully_verified FROM nanny_family_verifications nfv JOIN users u ON nfv.nanny_id=u.id WHERE nfv.created_at BETWEEN '{$from}' AND '{$to}' GROUP BY u.id,u.full_name ORDER BY total_families DESC");
    $verification_data['by_month']=dbFetchAll("SELECT nfv.month,COUNT(*) total_families,SUM(nfv.is_orphan_verified) orphan_verified,SUM(nfv.is_mother_contact_verified) mother_verified,SUM(nfv.is_bank_verified) bank_verified,SUM(CASE WHEN nfv.is_orphan_verified=1 AND nfv.is_mother_contact_verified=1 AND nfv.is_bank_verified=1 THEN 1 ELSE 0 END) fully_verified FROM nanny_family_verifications nfv WHERE nfv.created_at BETWEEN '{$from}' AND '{$to}' GROUP BY nfv.month ORDER BY nfv.month DESC");
}
include dirname(__DIR__,2) . '/includes/header.php';
?>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
<div class="welcome-section fade-in"><h2><i class="fas fa-tasks me-2"></i><?=e($pageTitle)?></h2><p class="text-muted"><?=e(t('operational.report_subtitle',['from'=>$from,'to'=>$to]))?></p></div>
<div class="card mb-4 fade-in shadow-sm"><div class="card-body"><form method="GET" class="row g-3 align-items-end"><input type="hidden" name="report" value="<?=e($report_type)?>"><div class="col-md-3"><label class="form-label fw-bold"><?=e(t('operational.from_date'))?></label><input type="date" name="from" class="form-control" value="<?=e($from)?>" required></div><div class="col-md-3"><label class="form-label fw-bold"><?=e(t('operational.to_date'))?></label><input type="date" name="to" class="form-control" value="<?=e($to)?>" required></div><div class="col-md-2"><button type="submit" class="btn btn-primary w-100" style="background-color:#1b4d8f;border-color:#1b4d8f"><i class="fas fa-filter me-1"></i><?=e(t('operational.apply_filter'))?></button></div></form></div></div>
<?php $reports=['supervisor'=>'operational.report_supervisor','nanny'=>'operational.report_nanny','verification'=>'operational.report_verification']; ?>
<ul class="nav nav-pills mb-4 fade-in flex-wrap gap-2"><?php foreach($reports as $key=>$label): ?><li class="nav-item"><a class="nav-link <?=$report_type===$key?'active':''?>" href="?report=<?=$key?>&from=<?=e($from)?>&to=<?=e($to)?>" style="<?=$report_type===$key?'background-color:#1b4d8f;color:white;':'color:#1b4d8f;background-color:#f8f9fa;'?>"><?=e(t($label))?></a></li><?php endforeach; ?></ul>
<div class="mb-3 text-end"><button onclick="exportToExcel()" class="btn btn-success me-2"><i class="fas fa-file-excel me-1"></i><?=e(t('operational.export_excel'))?></button><button onclick="exportToPDF()" class="btn btn-danger"><i class="fas fa-file-pdf me-1"></i><?=e(t('operational.export_pdf'))?></button></div>
<div id="report-content" class="fade-in">
<?php if($report_type==='supervisor'): ?><div class="card shadow-sm"><div class="card-header bg-white fw-bold" style="color:#1b4d8f"><i class="fas fa-user-tie me-2"></i><?=e(t('operational.supervisor_title'))?></div><div class="card-body"><div class="row g-4 mb-4">
<?php foreach([['operational.total_supervisors',$total_supervisors,'text-primary'],['operational.total_sponsors',$total_sponsors_all,'text-info'],['operational.activity_rate',$total_sponsors_all>0?round($active_sponsors_all/$total_sponsors_all*100,1):0,'text-success']] as [$label,$value,$cls]): ?><div class="col-md-4"><div class="card border-0 shadow-sm text-center bg-light"><div class="card-body"><h6 class="text-muted"><?=e(t($label))?></h6><div class="display-6 fw-bold <?=$cls?>"><?=number_format($value)?><?=$label==='operational.activity_rate'?'%':''?></div><?php if($label==='operational.total_sponsors'): ?><small class="text-success fw-bold"><?=number_format($active_sponsors_all)?> <?=e(t('operational.active'))?></small><?php endif; ?></div></div></div><?php endforeach; ?></div>
<div class="table-responsive"><table class="table table-bordered table-hover" id="report-table"><thead class="table-light"><tr><th><?=e(t('operational.supervisor'))?></th><th><?=e(t('operational.total_sponsors_short'))?></th><th><?=e(t('operational.active_sponsors_short'))?></th><th><?=e(t('operational.collection_count'))?></th><th><?=e(t('operational.total_collected'))?></th></tr></thead><tbody><?php foreach($supervisor_data as $row): ?><tr><td class="fw-bold"><?=e($row['full_name'])?></td><td><?=number_format($row['total_sponsors'])?></td><td><span class="badge bg-success"><?=number_format($row['active_sponsors'])?></span></td><td><?=number_format($row['transaction_count'])?></td><td class="text-success fw-bold"><?=number_format($row['total_collected'],2)?> <?=e(t('accounting.currency_sdg'))?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php elseif($report_type==='nanny'): ?><div class="card shadow-sm"><div class="card-header bg-white fw-bold" style="color:#1b4d8f"><i class="fas fa-hands-helping me-2"></i><?=e(t('operational.nanny_title'))?></div><div class="card-body"><div class="row g-4 mb-4"><?php foreach([['operational.total_nannies',$total_nannies,'text-primary'],['operational.disbursement_count',array_sum(array_column($nanny_data,'disbursement_count')),'text-info'],['operational.paid_families',array_sum(array_column($nanny_data,'paid_families')),'text-success'],['operational.returned_amounts',array_sum(array_column($nanny_data,'returned_amount')),'text-danger']] as [$label,$value,$cls]): ?><div class="col-md-3"><div class="card border-0 shadow-sm text-center bg-light"><div class="card-body"><h6 class="text-muted"><?=e(t($label))?></h6><div class="display-6 fw-bold <?=$cls?>"><?=number_format($value, $label==='operational.returned_amounts'?0:0)?></div></div></div></div><?php endforeach; ?></div><div class="table-responsive"><table class="table table-bordered table-hover" id="report-table"><thead class="table-light"><tr><th><?=e(t('operational.nanny'))?></th><th><?=e(t('operational.total_disbursements'))?></th><th><?=e(t('operational.total_amount'))?></th><th><?=e(t('operational.paid'))?></th><th><?=e(t('operational.pending'))?></th><th><?=e(t('operational.returned'))?></th><th><?=e(t('operational.returned_amount'))?></th></tr></thead><tbody><?php foreach($nanny_data as $row): ?><tr><td class="fw-bold"><?=e($row['full_name'])?></td><td><?=number_format($row['disbursement_count'])?></td><td class="fw-bold"><?=number_format($row['total_amount'],2)?> <?=e(t('accounting.currency_sdg'))?></td><td><span class="badge bg-success"><?=number_format($row['paid_families'])?></span></td><td><span class="badge bg-warning text-dark"><?=number_format($row['pending_families'])?></span></td><td><span class="badge bg-danger"><?=number_format($row['returned_families'])?></span></td><td class="text-danger"><?=number_format($row['returned_amount'],2)?> <?=e(t('accounting.currency_sdg'))?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php elseif($report_type==='verification'): $vs=$verification_data['summary']??[]; ?><div class="card shadow-sm mb-4"><div class="card-header bg-white fw-bold" style="color:#1b4d8f"><i class="fas fa-clipboard-check me-2"></i><?=e(t('operational.verification_summary'))?></div><div class="card-body"><div class="row g-4 mb-4"><?php foreach([['operational.total_verifications','total_verifications','text-primary'],['operational.orphan_verified','orphan_verified','text-success'],['operational.mother_verified','mother_verified','text-info'],['operational.fully_verified','fully_verified','text-primary']] as [$label,$field,$cls]): ?><div class="col-md-3"><div class="card border-0 shadow-sm text-center bg-light"><div class="card-body"><h6 class="text-muted"><?=e(t($label))?></h6><div class="display-6 fw-bold <?=$cls?>"><?=number_format($vs[$field]??0)?></div><?php if($field!=='total_verifications'): ?><small class="text-muted"><?=($vs['total_verifications']??0)>0?round(($vs[$field]??0)/($vs['total_verifications']??1)*100,1):0?>%</small><?php endif; ?></div></div></div><?php endforeach; ?></div><canvas id="verificationChart" style="max-height:300px"></canvas></div></div>
<?php foreach([['by_nanny','report-table-nanny','operational.verification_by_nanny'],['by_month','report-table-month','operational.verification_by_month']] as [$which,$id,$title]): ?><div class="card shadow-sm mb-4"><div class="card-header bg-white fw-bold" style="color:#1b4d8f"><i class="fas fa-<?=($which==='by_nanny'?'user-check':'calendar-alt')?> me-2"></i><?=e(t($title))?></div><div class="card-body"><div class="table-responsive"><table class="table table-bordered table-hover" id="<?=$id?>"><thead class="table-light"><tr><?php if($which==='by_nanny'): ?><th><?=e(t('operational.nanny'))?></th><?php else: ?><th><?=e(t('operational.month'))?></th><?php endif; ?><th><?=e(t('operational.total_families'))?></th><th><?=e(t('operational.orphan_check'))?></th><th><?=e(t('operational.mother_check'))?></th><th><?=e(t('operational.bank_check'))?></th><th><?=e(t('operational.full_verification'))?></th><?php if($which==='by_nanny'): ?><th><?=e(t('operational.full_verification_rate'))?></th><?php endif; ?></tr></thead><tbody><?php foreach($verification_data[$which] as $row): ?><?php $rate=($row['total_families']??0)>0?round(($row['fully_verified']??0)/$row['total_families']*100,1):0; ?><tr><td class="fw-bold"><?=e($which==='by_nanny'?$row['nanny_name']:$row['month'])?></td><td><?=number_format($row['total_families'])?></td><td class="text-success"><?=number_format($row['orphan_verified'])?></td><td class="text-info"><?=number_format($row['mother_verified'])?></td><td class="text-primary"><?=number_format($row['bank_verified'])?></td><td><span class="badge bg-success"><?=number_format($row['fully_verified'])?></span></td><?php if($which==='by_nanny'): ?><td><div class="progress" style="height:20px"><div class="progress-bar bg-success" style="width:<?=$rate?>%"><?=$rate?>%</div></div></td><?php endif; ?></tr><?php endforeach; ?></tbody></table></div></div></div><?php endforeach; ?>
<?php endif; ?></div>
<div class="mt-4 text-center"><a href="<?=APP_URL?>modules/reports/index.php?from=<?=e($from)?>&to=<?=e($to)?>" class="btn btn-outline-secondary"><i class="fas fa-arrow-right me-1"></i><?=e(t('operational.back_to_center'))?></a></div>
<script>
<?php if($report_type==='verification'&&!empty($verification_data['summary'])): ?>const vs=<?=json_encode($verification_data['summary'])?>;new Chart(document.getElementById('verificationChart').getContext('2d'),{type:'bar',data:{labels:[AKLang.t('operational.orphan_check'),AKLang.t('operational.mother_check'),AKLang.t('operational.bank_check'),AKLang.t('operational.full_verification')],datasets:[{label:AKLang.t('operational.verification_operations'),data:[+vs.orphan_verified||0,+vs.mother_verified||0,+vs.bank_verified||0,+vs.fully_verified||0],backgroundColor:['rgba(40,167,69,.7)','rgba(23,162,184,.7)','rgba(27,77,143,.7)','rgba(111,66,193,.7)'],borderWidth:1}]},options:{responsive:true,maintainAspectRatio:true,plugins:{legend:{display:false},title:{display:true,text:AKLang.t('operational.verification_distribution'),font:{size:14}}},scales:{y:{beginAtZero:true}}}});<?php endif; ?>
function exportToExcel(){const tables=document.querySelectorAll('#report-content table');if(!tables.length){alert(AKLang.t('operational.no_table_export'));return;}const wb=XLSX.utils.book_new();tables.forEach((table,index)=>XLSX.utils.book_append_sheet(wb,XLSX.utils.table_to_sheet(table),`Sheet${index+1}`));XLSX.writeFile(wb,'operational_report_<?=date('Y-m-d')?>.xlsx');}
function exportToPDF(){html2pdf().set({margin:.5,filename:'operational_report_<?=date('Y-m-d')?>.pdf',image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true},jsPDF:{unit:'in',format:'a4',orientation:'landscape'}}).from(document.getElementById('report-content')).save();}
</script>
<?php include dirname(__DIR__,2) . '/includes/footer.php'; ?>