<?php
declare(strict_types=1);
require_once __DIR__ . '/../../config/config.php';
require_once __DIR__ . '/../../config/database.php';
require_once __DIR__ . '/../../config/functions.php';
require_once __DIR__ . '/../../config/session.php';
Session::start();
$userRole=Session::getUserRole();
if(!Session::isLoggedIn()||!in_array($userRole,['hr_manager','hr_staff','admin'])){header('Location: '.APP_URL.'index.php');exit();}
$selected_date=$_GET['date']??date('Y-m-d'); $message=''; $msg_type='success';
if($_SERVER['REQUEST_METHOD']==='POST'){
    $action=$_POST['action']??'';
    $ids=isset($_POST['employee_ids'])&&is_array($_POST['employee_ids'])?array_values(array_filter(array_map('intval',$_POST['employee_ids']))):[];
    if(!$ids && isset($_POST['employee_id']))$ids=[(int)$_POST['employee_id']];
    try{
        if($action==='bulk_check_in'){
            $mode=$_POST['bulk_work_mode']??'remote';
            foreach($ids as $id)dbExecute("INSERT INTO attendance (employee_id,date,check_in,work_mode,status) VALUES (?, ?, ?, ?, 'present') ON DUPLICATE KEY UPDATE check_in=VALUES(check_in),work_mode=VALUES(work_mode),status='present'",[$id,$selected_date,date('H:i:s'),$mode]);
            $message='تم تسجيل الحضور للموظفين المحددين بنجاح.';
        }elseif($action==='bulk_check_out'){
            foreach($ids as $id)dbExecute("UPDATE attendance SET check_out=? WHERE employee_id=? AND date=?",[date('H:i:s'),$id,$selected_date]);
            $message='تم تسجيل الانصراف للموظفين المحددين.';
        }elseif($action==='bulk_absent'){
            foreach($ids as $id)dbExecute("INSERT INTO attendance (employee_id,date,status) VALUES (?,?,'absent') ON DUPLICATE KEY UPDATE status='absent'",[$id,$selected_date]);
            $message='تم تسجيل الغياب للموظفين المحددين.';
        }elseif($action==='bulk_leave'){
            foreach($ids as $id)dbExecute("INSERT INTO attendance (employee_id,date,status) VALUES (?,?,'on_leave') ON DUPLICATE KEY UPDATE status='on_leave'",[$id,$selected_date]);
            $message='تم تسجيل الإجازة للموظفين المحددين.';
        }elseif($action==='check_in'){
            $id=(int)($_POST['employee_id']??0);$mode=$_POST['work_mode']??'remote';
            dbExecute("INSERT INTO attendance (employee_id,date,check_in,work_mode,status) VALUES (?, ?, ?, ?, 'present') ON DUPLICATE KEY UPDATE check_in=VALUES(check_in),work_mode=VALUES(work_mode),status='present'",[$id,$selected_date,date('H:i:s'),$mode]);
            $message=t('hr.attendance_recorded');
        }elseif($action==='check_out'){
            $id=(int)($_POST['employee_id']??0);dbExecute("UPDATE attendance SET check_out=? WHERE employee_id=? AND date=?",[date('H:i:s'),$id,$selected_date]);$message=t('hr.checkout_recorded');
        }elseif($action==='mark_absent'){
            $id=(int)($_POST['employee_id']??0);dbExecute("INSERT INTO attendance (employee_id,date,status) VALUES (?,?,'absent') ON DUPLICATE KEY UPDATE status='absent'",[$id,$selected_date]);$message=t('hr.absence_recorded');
        }elseif($action==='mark_leave'){
            $id=(int)($_POST['employee_id']??0);dbExecute("INSERT INTO attendance (employee_id,date,status) VALUES (?,?,'on_leave') ON DUPLICATE KEY UPDATE status='on_leave'",[$id,$selected_date]);$message=t('hr.attendance_leave_recorded');
        }
    }catch(Throwable $e){$message=t('hr.attendance_error',['message'=>$e->getMessage()]);$msg_type='error';}
}
$employees=dbFetchAll("SELECT e.id,e.full_name,e.department_id,d.name_ar as dept_name FROM employees e LEFT JOIN departments d ON e.department_id=d.id WHERE e.status='active' ORDER BY e.full_name",[]);
$attendance_records=[];foreach(dbFetchAll("SELECT * FROM attendance WHERE date=?",[$selected_date]) as $att)$attendance_records[$att['employee_id']]=$att;
$stats=['present'=>0,'absent'=>0,'late'=>0,'on_leave'=>0,'remote'=>0,'onsite'=>0];foreach($attendance_records as $att){if(isset($stats[$att['status']]))$stats[$att['status']]++;if(isset($stats[$att['work_mode']]))$stats[$att['work_mode']]++;}
$pageTitle=t('hr.attendance_title');require_once __DIR__.'/../../includes/header.php';
?>
<style>
.att3{--ink:#172033;--muted:#667085;--line:#e6e9ee;--soft:#f7f8fa;--brand:#1b4d8f;background:#f5f6f8;margin:-10px -12px 0;padding:22px}.att3-head{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin-bottom:18px}.att3-title{font-size:1.4rem;font-weight:800;color:var(--ink);margin:0}.att3-sub{font-size:.78rem;color:var(--muted);margin-top:5px}.att3-date{display:flex;align-items:center;gap:5px}.att3-date a,.att3-date button{width:34px;height:34px;border:1px solid var(--line);background:#fff;border-radius:8px;color:#475467;display:inline-flex;align-items:center;justify-content:center;text-decoration:none}.att3-date input{height:34px;width:145px;border:1px solid var(--line);border-radius:8px;background:#fff;text-align:center;font-size:.78rem;font-weight:700;color:#344054;padding:0 7px}
.att3-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:14px}.kpi{background:#fff;border:1px solid var(--line);border-radius:10px;padding:10px 13px;display:flex;align-items:center;justify-content:space-between}.kpi-label{font-size:.7rem;color:var(--muted)}.kpi-num{font-size:1.15rem;font-weight:800;color:var(--ink);margin-top:2px}.kpi-mark{font-size:.85rem;width:30px;height:30px;border-radius:8px;display:flex;align-items:center;justify-content:center;background:var(--soft);color:#667085}.kpi.p .kpi-mark{background:#eaf7ef;color:#16804a}.kpi.l .kpi-mark{background:#fff5d7;color:#947000}.kpi.a .kpi-mark{background:#fdebed;color:#c73543}.kpi.lv .kpi-mark{background:#eaf5fb;color:#167395}
.att3-panel{background:#fff;border:1px solid var(--line);border-radius:12px;overflow:hidden}.att3-tools{padding:10px;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:7px;flex-wrap:wrap}.att3-search{position:relative;flex:1;min-width:220px}.att3-search input{height:35px;width:100%;border:1px solid var(--line);border-radius:8px;padding:0 32px 0 10px;font-size:.77rem}.att3-search i{position:absolute;right:11px;top:10px;color:#98a2b3;font-size:.72rem}.att3-tools select{height:35px;border:1px solid var(--line);border-radius:8px;padding:0 8px;font-size:.75rem;color:#475467;background:#fff;min-width:135px}.selection-bar{display:none;align-items:center;gap:7px;padding:8px 10px;background:#f1f6fc;border-bottom:1px solid #dbe7f5}.selection-bar.show{display:flex}.selection-count{font-size:.74rem;font-weight:800;color:var(--brand);margin-left:auto}.bulk-btn{height:30px;border:0;border-radius:7px;padding:0 9px;font-size:.7rem;font-weight:750;display:inline-flex;align-items:center;gap:5px;cursor:pointer}.bulk-in{background:#dff3e7;color:#176b40}.bulk-out{background:#fbe1e5;color:#a82e3b}.bulk-leave{background:#fff0bd;color:#785d00}.bulk-absent{background:#eceff3;color:#475467}.bulk-mode{height:30px;border:1px solid #d7e0eb;border-radius:7px;background:#fff;font-size:.7rem;padding:0 7px}
.att3-table{width:100%;border-collapse:separate;border-spacing:0}.att3-table th{height:38px;background:#fafbfc;border-bottom:1px solid var(--line);font-size:.67rem;font-weight:800;color:#667085;text-align:right;padding:0 12px;white-space:nowrap}.att3-table td{height:54px;border-bottom:1px solid #f0f1f3;padding:7px 12px;font-size:.76rem;color:#344054;vertical-align:middle}.att3-table tbody tr:hover{background:#fbfcfe}.att3-table tbody tr:last-child td{border-bottom:0}.check-col{width:38px;text-align:center!important}.row-check,.head-check{width:15px;height:15px;accent-color:var(--brand);cursor:pointer}.person{display:flex;align-items:center;gap:8px;min-width:185px}.person-avatar{width:31px;height:31px;border-radius:50%;background:#edf3fb;color:var(--brand);display:flex;align-items:center;justify-content:center;font-size:.7rem;font-weight:800;flex:none}.person-name{font-size:.77rem;font-weight:800;color:#273444}.person-meta{font-size:.65rem;color:#98a2b3;margin-top:1px}.dept3{color:#667085;font-size:.72rem}.time3{font-variant-numeric:tabular-nums;font-weight:700;color:#344054}.time3.empty{font-weight:500;color:#adb5bd}.mode3{font-size:.67rem;font-weight:700;padding:3px 7px;background:#f1f3f5;border-radius:5px;color:#596579}.status3{display:inline-flex;align-items:center;gap:4px;border-radius:15px;padding:3px 8px;font-size:.67rem;font-weight:800}.status3.p{background:#eaf7ef;color:#167447}.status3.l{background:#fff5d7;color:#8a6700}.status3.a{background:#fdebed;color:#b42331}.status3.lv{background:#eaf5fb;color:#126c8e}.status3.e{background:#eef0f3;color:#667085}.row-action{display:flex;justify-content:flex-end;gap:5px;align-items:center}.row-action select{height:29px;border:1px solid var(--line);border-radius:6px;font-size:.68rem;padding:0 5px;max-width:95px}.row-btn{height:29px;border:0;border-radius:6px;padding:0 8px;font-size:.68rem;font-weight:750;cursor:pointer}.row-in{background:#eaf7ef;color:#167447}.row-out{background:#fdebed;color:#b42331}.row-leave{background:#fff4cf;color:#7b5c00}.done{font-size:.68rem;color:#98a2b3;display:inline-flex;align-items:center;gap:4px}.empty3{text-align:center!important;padding:35px!important;color:#98a2b3}
@media(max-width:950px){.att3{padding:16px}.att3-kpis{grid-template-columns:repeat(2,1fr)}.att3-table{min-width:920px}.att3-panel{overflow-x:auto}.att3-tools,.selection-bar{position:relative}}@media(max-width:600px){.att3-head{align-items:stretch;flex-direction:column}.att3-kpis{grid-template-columns:1fr 1fr}}
</style>
<div class="att3">
<div class="att3-head"><div><h1 class="att3-title"><i class="fas fa-calendar-check me-2" style="color:#1b4d8f"></i><?php echo e(t('hr.attendance_title')); ?></h1><div class="att3-sub">إدارة حضور وانصراف الموظفين بشكل يومي مع تنفيذ الإجراءات الفردية أو الجماعية.</div></div><div class="att3-date"><a href="?date=<?php echo htmlspecialchars(date('Y-m-d',strtotime($selected_date.' -1 day'))); ?>" title="اليوم السابق"><i class="fas fa-chevron-right"></i></a><form method="GET" class="m-0"><input type="date" name="date" value="<?php echo htmlspecialchars($selected_date); ?>" onchange="this.form.submit()"></form><a href="?date=<?php echo htmlspecialchars(date('Y-m-d',strtotime($selected_date.' +1 day'))); ?>" title="اليوم التالي"><i class="fas fa-chevron-left"></i></a></div></div>
<?php if($message): ?><div class="alert alert-<?php echo $msg_type==='error'?'danger':'success'; ?> py-2 px-3 mb-3" style="border-radius:8px;font-size:.78rem"><?php echo e($message); ?><button type="button" class="btn-close"></button></div><?php endif; ?>
<div class="att3-kpis"><div class="kpi p"><div><div class="kpi-label"><?php echo e(t('hr.present')); ?></div><div class="kpi-num"><?php echo $stats['present']; ?></div></div><div class="kpi-mark"><i class="fas fa-check"></i></div></div><div class="kpi l"><div><div class="kpi-label"><?php echo e(t('hr.late')); ?></div><div class="kpi-num"><?php echo $stats['late']; ?></div></div><div class="kpi-mark"><i class="fas fa-clock"></i></div></div><div class="kpi a"><div><div class="kpi-label"><?php echo e(t('hr.absent')); ?></div><div class="kpi-num"><?php echo $stats['absent']; ?></div></div><div class="kpi-mark"><i class="fas fa-user-xmark"></i></div></div><div class="kpi lv"><div><div class="kpi-label"><?php echo e(t('hr.on_leave')); ?></div><div class="kpi-num"><?php echo $stats['on_leave']; ?></div></div><div class="kpi-mark"><i class="fas fa-calendar-day"></i></div></div></div>
<div class="att3-panel">
<div class="att3-tools"><div class="att3-search"><i class="fas fa-search"></i><input id="attSearch" type="search" placeholder="البحث باسم الموظف..." autocomplete="off"></div><select id="attDept"><option value="">كل الأقسام</option><?php $deps=[];foreach($employees as $e){if(!empty($e['dept_name']))$deps[$e['department_id']]=$e['dept_name'];}foreach($deps as $d): ?><option value="<?php echo htmlspecialchars($d); ?>"><?php echo htmlspecialchars($d); ?></option><?php endforeach; ?></select><select id="attStatus"><option value="">كل الحالات</option><option value="present"><?php echo e(t('hr.present')); ?></option><option value="late"><?php echo e(t('hr.late')); ?></option><option value="absent"><?php echo e(t('hr.absent')); ?></option><option value="on_leave"><?php echo e(t('hr.on_leave')); ?></option></select></div>
<form method="POST" id="bulkForm"><input type="hidden" name="selected_date" value="<?php echo htmlspecialchars($selected_date); ?>"><div class="selection-bar" id="selectionBar"><select name="bulk_work_mode" class="bulk-mode"><option value="remote"><?php echo e(t('hr.work_mode_remote')); ?></option><option value="onsite"><?php echo e(t('hr.work_mode_onsite')); ?></option><option value="hybrid"><?php echo e(t('hr.work_mode_hybrid')); ?></option></select><button type="submit" name="action" value="bulk_check_in" class="bulk-btn bulk-in"><i class="fas fa-right-to-bracket"></i> تسجيل حضور</button><button type="submit" name="action" value="bulk_check_out" class="bulk-btn bulk-out"><i class="fas fa-right-from-bracket"></i> تسجيل انصراف</button><button type="submit" name="action" value="bulk_leave" class="bulk-btn bulk-leave"><i class="fas fa-calendar-check"></i> إجازة</button><button type="submit" name="action" value="bulk_absent" class="bulk-btn bulk-absent"><i class="fas fa-user-xmark"></i> غياب</button><span class="selection-count" id="selectionCount">0 محدد</span></div>
<div class="table-responsive"><table class="att3-table" id="attTable"><thead><tr><th class="check-col"><input class="head-check" id="selectAll" type="checkbox" title="تحديد الكل"></th><th><?php echo e(t('hr.employee')); ?></th><th><?php echo e(t('groups.group')); ?></th><th><?php echo e(t('hr.check_in')); ?></th><th><?php echo e(t('hr.check_out')); ?></th><th>النمط</th><th><?php echo e(t('common.status')); ?></th><th class="text-end"><?php echo e(t('common.actions')); ?></th></tr></thead><tbody>
<?php if(empty($employees)): ?><tr><td colspan="8" class="empty3">لا يوجد موظفون نشطون.</td></tr><?php else: foreach($employees as $emp): $att=$attendance_records[$emp['id']]??null;$status=$att['status']??'absent';$work_mode=$att['work_mode']??'';$initial=mb_substr(trim((string)$emp['full_name']),0,1,'UTF-8');$sc=['present'=>'p','late'=>'l','absent'=>'a','on_leave'=>'lv','half_day'=>'e'];$si=['present'=>'fa-check','late'=>'fa-clock','absent'=>'fa-user-xmark','on_leave'=>'fa-calendar-check','half_day'=>'fa-minus'];$sl=['present'=>'hr.present','late'=>'hr.late','absent'=>'hr.absent','on_leave'=>'hr.on_leave','half_day'=>'hr.half_day']; ?>
<tr data-name="<?php echo htmlspecialchars(mb_strtolower((string)$emp['full_name'],'UTF-8')); ?>" data-dept="<?php echo htmlspecialchars((string)($emp['dept_name']??'')); ?>" data-status="<?php echo htmlspecialchars($status); ?>"><td class="check-col"><input class="row-check" type="checkbox" name="employee_ids[]" value="<?php echo (int)$emp['id']; ?>"></td><td><div class="person"><div class="person-avatar"><?php echo htmlspecialchars($initial); ?></div><div><div class="person-name"><?php echo htmlspecialchars($emp['full_name']); ?></div><div class="person-meta">ID #<?php echo (int)$emp['id']; ?></div></div></div></td><td class="dept3"><?php echo htmlspecialchars($emp['dept_name']??'-'); ?></td><td><span class="time3 <?php echo (!$att||!$att['check_in'])?'empty':''; ?>"><?php echo ($att&&$att['check_in'])?substr($att['check_in'],0,5):'--:--'; ?></span></td><td><span class="time3 <?php echo (!$att||!$att['check_out'])?'empty':''; ?>"><?php echo ($att&&$att['check_out'])?substr($att['check_out'],0,5):'--:--'; ?></span></td><td><span class="mode3"><?php $modes=['remote'=>'hr.work_mode_remote','onsite'=>'hr.work_mode_onsite','hybrid'=>'hr.work_mode_hybrid'];echo $att?e(t($modes[$work_mode]??'hr.work_mode_remote')):'—'; ?></span></td><td><span class="status3 <?php echo $sc[$status]??'e'; ?>"><i class="fas <?php echo $si[$status]??'fa-minus'; ?>"></i><?php echo e(t($sl[$status]??'common.status')); ?></span></td><td class="text-end"><div class="row-action"><?php if(!$att||!$att['check_in']): ?><form method="POST" class="m-0"><input type="hidden" name="action" value="check_in"><input type="hidden" name="employee_id" value="<?php echo $emp['id']; ?>"><select name="work_mode"><option value="remote"><?php echo e(t('hr.work_mode_remote')); ?></option><option value="onsite"><?php echo e(t('hr.work_mode_onsite')); ?></option></select><button class="row-btn row-in" type="submit"><i class="fas fa-right-to-bracket"></i></button></form><?php elseif(!$att['check_out']): ?><form method="POST" class="m-0"><input type="hidden" name="action" value="check_out"><input type="hidden" name="employee_id" value="<?php echo $emp['id']; ?>"><button class="row-btn row-out" type="submit" title="<?php echo e(t('hr.check_out')); ?>"><i class="fas fa-right-from-bracket"></i></button></form><?php else: ?><span class="done"><i class="fas fa-circle-check"></i><?php echo e(t('hr.complete')); ?></span><?php endif; ?><?php if(!$att||$att['status']==='absent'): ?><form method="POST" class="m-0"><input type="hidden" name="action" value="mark_leave"><input type="hidden" name="employee_id" value="<?php echo $emp['id']; ?>"><button class="row-btn row-leave" type="submit" title="<?php echo e(t('hr.leave')); ?>"><i class="fas fa-calendar-check"></i></button></form><?php endif; ?></div></td></tr>
<?php endforeach; endif; ?></tbody></table></div></form></div></div>
<script>
document.addEventListener('DOMContentLoaded',function(){const table=document.getElementById('attTable'),all=document.getElementById('selectAll'),bar=document.getElementById('selectionBar'),count=document.getElementById('selectionCount'),search=document.getElementById('attSearch'),dept=document.getElementById('attDept'),status=document.getElementById('attStatus'),form=document.getElementById('bulkForm');function rows(){return Array.from(table.querySelectorAll('tbody tr[data-name]'));}function checks(){return rows().filter(r=>r.style.display!=='none').map(r=>r.querySelector('.row-check')).filter(Boolean)}function refresh(){const visible=checks(),selected=visible.filter(c=>c.checked);count.textContent=selected.length+' محدد';bar.classList.toggle('show',selected.length>0);all.checked=visible.length>0&&selected.length===visible.length;all.indeterminate=selected.length>0&&selected.length<visible.length;}function filter(){const q=(search.value||'').trim().toLocaleLowerCase();rows().forEach(r=>{r.style.display=(!q||r.dataset.name.includes(q))&&(!dept.value||r.dataset.dept===dept.value)&&(!status.value||r.dataset.status===status.value)?'':'none';});refresh();}all.addEventListener('change',function(){checks().forEach(c=>c.checked=all.checked);refresh();});table.addEventListener('change',function(e){if(e.target.classList.contains('row-check'))refresh();});search.addEventListener('input',filter);dept.addEventListener('change',filter);status.addEventListener('change',filter);form.addEventListener('submit',function(e){if(!checks().some(c=>c.checked)){e.preventDefault();alert('يرجى تحديد موظف واحد على الأقل.');}});});
</script>
<?php require_once __DIR__.'/../../includes/footer.php'; ?>