<?php
declare(strict_types=1);
require_once __DIR__ . '/../../config/config.php';
require_once __DIR__ . '/../../config/database.php';
require_once __DIR__ . '/../../config/functions.php';
require_once __DIR__ . '/../../config/session.php';
Session::start();
$userRole=Session::getUserRole();
if(!Session::isLoggedIn()||!in_array($userRole,['hr_manager','hr_staff','admin'])){header('Location: '.APP_URL.'index.php');exit();}
$selected_date=$_GET['date']??date('Y-m-d'); $message=''; $msg_type='success';
if($_SERVER['REQUEST_METHOD']==='POST'){
    $action=$_POST['action']??''; $emp_id=(int)($_POST['employee_id']??0);
    try{
        if($action==='check_in'){
            $work_mode=$_POST['work_mode']??'remote'; $check_in_time=date('H:i:s');
            dbExecute("INSERT INTO attendance (employee_id, date, check_in, work_mode, status) VALUES (?, ?, ?, ?, 'present') ON DUPLICATE KEY UPDATE check_in = VALUES(check_in), work_mode = VALUES(work_mode), status = 'present'",[$emp_id,$selected_date,$check_in_time,$work_mode]);
            $message=t('hr.attendance_recorded');
        }elseif($action==='check_out'){
            dbExecute("UPDATE attendance SET check_out = ? WHERE employee_id = ? AND date = ?",[date('H:i:s'),$emp_id,$selected_date]); $message=t('hr.checkout_recorded');
        }elseif($action==='mark_absent'){
            dbExecute("INSERT INTO attendance (employee_id, date, status) VALUES (?, ?, 'absent') ON DUPLICATE KEY UPDATE status = 'absent'",[$emp_id,$selected_date]); $message=t('hr.absence_recorded');
        }elseif($action==='mark_leave'){
            dbExecute("INSERT INTO attendance (employee_id, date, status) VALUES (?, ?, 'on_leave') ON DUPLICATE KEY UPDATE status = 'on_leave'",[$emp_id,$selected_date]); $message=t('hr.attendance_leave_recorded');
        }
    }catch(Throwable $e){$message=t('hr.attendance_error',['message'=>$e->getMessage()]);$msg_type='error';}
}
$employees=dbFetchAll("SELECT e.id,e.full_name,e.department_id,d.name_ar as dept_name FROM employees e LEFT JOIN departments d ON e.department_id=d.id WHERE e.status='active' ORDER BY e.full_name",[]);
$attendance_records=[]; $att_list=dbFetchAll("SELECT * FROM attendance WHERE date = ?",[$selected_date]);
foreach($att_list as $att)$attendance_records[$att['employee_id']]=$att;
$stats=['present'=>0,'absent'=>0,'late'=>0,'on_leave'=>0,'remote'=>0,'onsite'=>0];
foreach($attendance_records as $att){if(isset($stats[$att['status']]))$stats[$att['status']]++;if(isset($stats[$att['work_mode']]))$stats[$att['work_mode']]++;}
$pageTitle=t('hr.attendance_title'); require_once __DIR__.'/../../includes/header.php';
?>
<style>
.att-page{--navy:#1b4d8f;--line:#e9edf2;--muted:#6c757d}.att-hero{background:#fff;border:1px solid var(--line);border-radius:14px;padding:20px 22px;margin-bottom:16px;box-shadow:0 2px 8px rgba(20,35,55,.04)}
.att-hero h1{font-size:1.35rem;margin:0 0 4px;font-weight:800;color:#1d2a3a}.att-hero p{margin:0;color:var(--muted);font-size:.84rem}.date-nav{display:flex;align-items:center;gap:7px}.date-nav .date-box{min-width:155px;text-align:center;font-weight:700;font-size:.86rem}.date-nav .btn{border:1px solid var(--line);background:#fff;color:#344054;border-radius:8px;padding:7px 10px}.date-nav .btn:hover{background:#f6f8fa}
.att-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:16px}.sum-card{background:#fff;border:1px solid var(--line);border-radius:11px;padding:11px 14px;display:flex;align-items:center;gap:11px}.sum-icon{width:34px;height:34px;border-radius:9px;display:flex;align-items:center;justify-content:center;background:#f2f5f9;color:#536273}.sum-card.present .sum-icon{background:#eaf7ef;color:#198754}.sum-card.late .sum-icon{background:#fff7df;color:#9a7200}.sum-card.absent .sum-icon{background:#fdebed;color:#c93645}.sum-card.leave .sum-icon{background:#eaf5fb;color:#16749a}.sum-value{font-weight:800;font-size:1.15rem;line-height:1}.sum-label{font-size:.72rem;color:var(--muted);margin-top:4px}
.att-toolbar{background:#fff;border:1px solid var(--line);border-radius:11px;padding:11px;margin-bottom:12px;display:flex;gap:8px;align-items:center;flex-wrap:wrap}.att-toolbar .search{flex:1;min-width:220px;position:relative}.att-toolbar input,.att-toolbar select{height:37px;border:1px solid #d9dee5;border-radius:8px;font-size:.82rem}.att-toolbar input{width:100%;padding:0 34px 0 11px}.att-toolbar select{min-width:150px;padding:0 9px}.search i{position:absolute;right:11px;top:11px;color:#98a2b3;font-size:.78rem}
.att-panel{background:#fff;border:1px solid var(--line);border-radius:13px;overflow:hidden;box-shadow:0 2px 8px rgba(20,35,55,.04)}.att-panel-head{padding:13px 16px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}.att-panel-title{font-weight:800;color:#253246;font-size:.9rem}.att-count{font-size:.72rem;color:#667085;background:#f5f7fa;padding:5px 9px;border-radius:20px}
.att-table{width:100%;border-collapse:separate;border-spacing:0}.att-table th{background:#f8fafc;color:#667085;font-size:.7rem;font-weight:800;padding:10px 13px;border-bottom:1px solid var(--line);white-space:nowrap}.att-table td{padding:11px 13px;border-bottom:1px solid #f0f2f5;font-size:.8rem;vertical-align:middle}.att-table tbody tr:hover{background:#fbfcfe}.att-table tbody tr:last-child td{border-bottom:0}.employee{display:flex;align-items:center;gap:9px;min-width:180px}.avatar{width:34px;height:34px;border-radius:50%;background:#edf3fb;color:var(--navy);display:flex;align-items:center;justify-content:center;font-weight:800;font-size:.78rem;flex:none}.employee-name{font-weight:750;color:#273444;line-height:1.25}.employee-sub{font-size:.68rem;color:#98a2b3;margin-top:2px}.dept{color:#596579;font-size:.76rem}.time-box{display:inline-flex;align-items:center;gap:5px;min-width:64px;font-weight:700;color:#344054}.time-box i{font-size:.68rem;color:#98a2b3}.mode{display:inline-flex;padding:4px 8px;border-radius:6px;background:#f4f6f8;color:#596579;font-size:.7rem;font-weight:700}.status{display:inline-flex;align-items:center;gap:5px;padding:4px 9px;border-radius:20px;font-size:.7rem;font-weight:800;white-space:nowrap}.status.present{background:#eaf7ef;color:#167447}.status.late{background:#fff6d9;color:#8a6500}.status.absent{background:#fdebed;color:#b42331}.status.leave{background:#eaf5fb;color:#126c8e}.status.empty{background:#f2f4f7;color:#667085}.action-cell{min-width:210px}.action-form{display:flex;align-items:center;justify-content:flex-end;gap:5px}.action-form select{height:31px;border:1px solid #d9dee5;border-radius:7px;font-size:.72rem;padding:0 6px;max-width:105px}.action-btn{height:31px;border:0;border-radius:7px;padding:0 10px;font-size:.72rem;font-weight:750;display:inline-flex;align-items:center;gap:5px;cursor:pointer}.action-in{background:#eaf7ef;color:#167447}.action-in:hover{background:#d9f0e2}.action-out{background:#fdebed;color:#b42331}.action-out:hover{background:#f8dce0}.action-leave{background:#fff6d9;color:#806000}.action-leave:hover{background:#ffefbf}.complete{font-size:.72rem;color:#98a2b3;display:inline-flex;align-items:center;gap:5px}.empty-row{text-align:center;padding:35px!important;color:#98a2b3}.empty-row i{font-size:1.5rem;display:block;margin-bottom:7px}
@media(max-width:1000px){.att-summary{grid-template-columns:repeat(2,1fr)}.att-table th:nth-child(2),.att-table td:nth-child(2){display:none}.action-cell{min-width:175px}}@media(max-width:700px){.att-summary{grid-template-columns:1fr 1fr}.att-hero{padding:16px}.date-nav{width:100%;margin-top:12px}.date-nav .date-box{flex:1}.att-table th:nth-child(5),.att-table td:nth-child(5){display:none}.att-panel{overflow-x:auto}.att-table{min-width:760px}}
</style>
<div class="att-page">
<div class="att-hero"><div class="d-flex justify-content-between align-items-center flex-wrap gap-3"><div><h1><i class="fas fa-user-clock me-2" style="color:#1b4d8f"></i><?php echo e(t('hr.attendance_title')); ?></h1><p><?php echo e(t('hr.attendance_intro',['date'=>date('Y-m-d',strtotime($selected_date))])); ?></p></div><div class="date-nav"><a class="btn" href="?date=<?php echo htmlspecialchars(date('Y-m-d',strtotime($selected_date.' -1 day'))); ?>" title="<?php echo e(t('hr.previous_day')??'اليوم السابق'); ?>"><i class="fas fa-chevron-right"></i></a><form method="GET" class="m-0"><input type="date" name="date" class="form-control date-box" value="<?php echo htmlspecialchars($selected_date); ?>" onchange="this.form.submit()"></form><a class="btn" href="?date=<?php echo htmlspecialchars(date('Y-m-d',strtotime($selected_date.' +1 day'))); ?>" title="<?php echo e(t('hr.next_day')??'اليوم التالي'); ?>"><i class="fas fa-chevron-left"></i></a></div></div></div>
<?php if($message): ?><div class="alert alert-<?php echo $msg_type==='error'?'danger':'success'; ?> py-2 px-3 mb-3" style="border-radius:9px;font-size:.82rem"><?php echo e($message); ?><button type="button" class="btn-close" data-bs-dismiss="alert"></button></div><?php endif; ?>
<div class="att-summary"><div class="sum-card present"><div class="sum-icon"><i class="fas fa-check"></i></div><div><div class="sum-value"><?php echo $stats['present']; ?></div><div class="sum-label"><?php echo e(t('hr.present')); ?></div></div></div><div class="sum-card late"><div class="sum-icon"><i class="fas fa-clock"></i></div><div><div class="sum-value"><?php echo $stats['late']; ?></div><div class="sum-label"><?php echo e(t('hr.late')); ?></div></div></div><div class="sum-card absent"><div class="sum-icon"><i class="fas fa-xmark"></i></div><div><div class="sum-value"><?php echo $stats['absent']; ?></div><div class="sum-label"><?php echo e(t('hr.absent')); ?></div></div></div><div class="sum-card leave"><div class="sum-icon"><i class="fas fa-calendar-check"></i></div><div><div class="sum-value"><?php echo $stats['on_leave']; ?></div><div class="sum-label"><?php echo e(t('hr.on_leave')); ?></div></div></div></div>
<div class="att-toolbar"><div class="search"><i class="fas fa-search"></i><input type="search" id="employeeSearch" placeholder="البحث عن موظف..." autocomplete="off"></div><select id="departmentFilter"><option value="">كل الأقسام</option><?php $departments=[];foreach($employees as $e){if(!empty($e['dept_name']))$departments[$e['department_id']]=$e['dept_name'];}foreach($departments as $d): ?><option value="<?php echo htmlspecialchars((string)$d); ?>"><?php echo htmlspecialchars($d); ?></option><?php endforeach; ?></select><select id="statusFilter"><option value="">كل الحالات</option><option value="present"><?php echo e(t('hr.present')); ?></option><option value="late"><?php echo e(t('hr.late')); ?></option><option value="absent"><?php echo e(t('hr.absent')); ?></option><option value="on_leave"><?php echo e(t('hr.on_leave')); ?></option></select></div>
<div class="att-panel"><div class="att-panel-head"><div class="att-panel-title"><i class="fas fa-list-check me-1"></i><?php echo e(t('hr.attendance_records',['date'=>date('Y-m-d',strtotime($selected_date))])); ?></div><span class="att-count"><?php echo e(t('hr.active_employee_count',['count'=>count($employees)])); ?></span></div><div class="table-responsive"><table class="att-table" id="attendanceTable"><thead><tr><th><?php echo e(t('hr.employee')); ?></th><th><?php echo e(t('groups.group')); ?></th><th><?php echo e(t('hr.check_in')); ?></th><th><?php echo e(t('hr.check_out')); ?></th><th>نمط العمل</th><th><?php echo e(t('common.status')); ?></th><th class="text-end"><?php echo e(t('common.actions')); ?></th></tr></thead><tbody>
<?php if(empty($employees)): ?><tr><td colspan="7" class="empty-row"><i class="fas fa-users-slash"></i><?php echo e(t('hr.no_active_employees')); ?></td></tr><?php else: foreach($employees as $emp): $att=$attendance_records[$emp['id']]??null;$status=$att['status']??'absent';$work_mode=$att['work_mode']??'';$initial=mb_substr(trim((string)$emp['full_name']),0,1,'UTF-8');$statusClass=['present'=>'present','late'=>'late','absent'=>'absent','on_leave'=>'leave','half_day'=>'empty'];$statusIcon=['present'=>'fa-check','late'=>'fa-clock','absent'=>'fa-xmark','on_leave'=>'fa-calendar-check','half_day'=>'fa-minus'];$statusLabel=['present'=>'hr.present','late'=>'hr.late','absent'=>'hr.absent','on_leave'=>'hr.on_leave','half_day'=>'hr.half_day']; ?>
<tr data-name="<?php echo htmlspecialchars(mb_strtolower((string)$emp['full_name'],'UTF-8')); ?>" data-dept="<?php echo htmlspecialchars((string)($emp['dept_name']??'')); ?>" data-status="<?php echo htmlspecialchars($status); ?>"><td><div class="employee"><div class="avatar"><?php echo htmlspecialchars($initial); ?></div><div><div class="employee-name"><?php echo htmlspecialchars($emp['full_name']); ?></div><div class="employee-sub">#<?php echo (int)$emp['id']; ?></div></div></div></td><td class="dept"><?php echo htmlspecialchars($emp['dept_name']??'-'); ?></td><td><span class="time-box"><i class="fas fa-arrow-right-to-bracket"></i><?php echo ($att&&$att['check_in'])?substr($att['check_in'],0,5):'--:--'; ?></span></td><td><span class="time-box"><i class="fas fa-arrow-right-from-bracket"></i><?php echo ($att&&$att['check_out'])?substr($att['check_out'],0,5):'--:--'; ?></span></td><td><span class="mode"><?php $modes=['remote'=>'hr.work_mode_remote','onsite'=>'hr.work_mode_onsite','hybrid'=>'hr.work_mode_hybrid'];echo $att?e(t($modes[$work_mode]??'hr.work_mode_remote')):'—'; ?></span></td><td><span class="status <?php echo $statusClass[$status]??'empty'; ?>"><i class="fas <?php echo $statusIcon[$status]??'fa-minus'; ?>"></i><?php echo e(t($statusLabel[$status]??'common.status')); ?></span></td><td class="action-cell text-end"><?php if(!$att||!$att['check_in']): ?><form method="POST" class="action-form"><input type="hidden" name="action" value="check_in"><input type="hidden" name="employee_id" value="<?php echo $emp['id']; ?>"><select name="work_mode" required><option value="remote"><?php echo e(t('hr.work_mode_remote')); ?></option><option value="onsite"><?php echo e(t('hr.work_mode_onsite')); ?></option></select><button class="action-btn action-in" type="submit"><i class="fas fa-right-to-bracket"></i><?php echo e(t('hr.check_in')); ?></button></form><?php elseif(!$att['check_out']): ?><form method="POST" class="action-form"><input type="hidden" name="action" value="check_out"><input type="hidden" name="employee_id" value="<?php echo $emp['id']; ?>"><button class="action-btn action-out" type="submit"><i class="fas fa-right-from-bracket"></i><?php echo e(t('hr.check_out')); ?></button></form><?php else: ?><span class="complete"><i class="fas fa-circle-check"></i><?php echo e(t('hr.complete')); ?></span><?php endif; ?><?php if(!$att||$att['status']==='absent'): ?><form method="POST" class="action-form"><input type="hidden" name="action" value="mark_leave"><input type="hidden" name="employee_id" value="<?php echo $emp['id']; ?>"><button class="action-btn action-leave" type="submit"><i class="fas fa-calendar-check"></i><?php echo e(t('hr.leave')); ?></button></form><?php endif; ?></td></tr>
<?php endforeach; endif; ?></tbody></table></div></div></div>
<script>
document.addEventListener('DOMContentLoaded',function(){const search=document.getElementById('employeeSearch'),dept=document.getElementById('departmentFilter'),status=document.getElementById('statusFilter');function filter(){const q=(search.value||'').trim().toLocaleLowerCase();document.querySelectorAll('#attendanceTable tbody tr[data-name]').forEach(r=>{const okName=!q||r.dataset.name.includes(q),okDept=!dept.value||r.dataset.dept===dept.value,okStatus=!status.value||r.dataset.status===status.value;r.style.display=okName&&okDept&&okStatus?'':'none';});}search.addEventListener('input',filter);dept.addEventListener('change',filter);status.addEventListener('change',filter);});
</script>
<?php require_once __DIR__.'/../../includes/footer.php'; ?>