<?php
declare(strict_types=1);
require_once __DIR__ . '/../../config/config.php';
require_once __DIR__ . '/../../config/database.php';
require_once __DIR__ . '/../../config/functions.php';
require_once __DIR__ . '/../../config/session.php';
Session::start();
$userRole = Session::getUserRole();
if (!Session::isLoggedIn() || !in_array($userRole, ['hr_manager', 'hr_staff', 'admin'])) { header('Location: ' . APP_URL . 'index.php'); exit(); }
$message = ''; $msg_type = 'success'; $filter = $_GET['status'] ?? 'all';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['action'] ?? '';
    try {
        if ($action === 'add') {
            $emp_id=(int)$_POST['employee_id']; $type=trim($_POST['contract_type']); $start=$_POST['start_date']; $end=$_POST['end_date'] ?: null; $salary=(float)$_POST['salary']; $terms=trim($_POST['terms']);
            $pdo->prepare("INSERT INTO contracts (employee_id, contract_type, start_date, end_date, salary, terms, status) VALUES (?, ?, ?, ?, ?, ?, 'active')")->execute([$emp_id,$type,$start,$end,$salary,$terms]);
            $message=t('hr.contract_added');
        } elseif ($action === 'update_status') {
            $id=(int)$_POST['contract_id']; $status=$_POST['status']; $pdo->prepare("UPDATE contracts SET status = ? WHERE id = ?")->execute([$status,$id]); $message=t('hr.contract_status_updated');
        }
    } catch (Exception $e) { $message=t('hr.error',['message'=>$e->getMessage()]); $msg_type='error'; }
}
$employees=dbFetchAll("SELECT id, full_name FROM employees WHERE status = 'active' ORDER BY full_name", []);
$sql="SELECT c.*, e.full_name as emp_name FROM contracts c JOIN employees e ON c.employee_id = e.id";
if($filter!=='all'){ $sql.=" WHERE c.status = ? ORDER BY c.end_date ASC"; $contracts=dbFetchAll($sql,[$filter]); } else { $sql.=" ORDER BY c.end_date ASC"; $contracts=dbFetchAll($sql,[]); }
$pageTitle=t('hr.contracts_title'); require_once __DIR__ . '/../../includes/header.php';
?>
<style>
.fm-header{background:linear-gradient(135deg,#1b4d8f 0%,#2c5aa0 100%);color:#fff;padding:25px;border-radius:12px;margin-bottom:25px}.fm-header h1{margin:0;font-size:1.8rem}.fm-header p{margin:5px 0 0;opacity:.9}.fm-card{background:#fff;border-radius:12px;box-shadow:0 2px 10px rgba(0,0,0,.06);margin-bottom:20px;overflow:hidden}.fm-card-head{background:#1b4d8f;color:#fff;padding:12px 18px;font-weight:700;font-size:1rem;display:flex;justify-content:space-between;align-items:center}.fm-card-body{padding:20px}.fm-table{width:100%;border-collapse:collapse}.fm-table th,.fm-table td{padding:10px 12px;border-bottom:1px solid #eee;text-align:right;font-size:.9rem}.fm-table th{background:#f8f9fa;font-weight:700;color:#1b4d8f}.fm-table tr:hover{background:#f8f9fa}.badge-fm{padding:4px 10px;border-radius:12px;font-size:.75rem;font-weight:700}.badge-green{background:#d4edda;color:#155724}.badge-amber{background:#fff3cd;color:#856404}.badge-red{background:#f8d7da;color:#721c24}.badge-gray{background:#e9ecef;color:#6c757d}.btn-fm{display:inline-block;padding:6px 12px;border-radius:6px;border:none;cursor:pointer;font-weight:700;text-decoration:none;font-size:.8rem;margin:2px}.btn-navy{background:#1b4d8f;color:#fff}.btn-danger{background:#dc3545;color:#fff}.form-label{font-weight:600;color:#495057;margin-bottom:.5rem}.form-control,.form-select{border-radius:6px;border:1px solid #ced4da;padding:.5rem .8rem}.tabs{display:flex;gap:5px;margin-bottom:20px;border-bottom:2px solid #eee;padding-bottom:10px}.tab{padding:8px 16px;border-radius:6px 6px 0 0;text-decoration:none;color:#666;font-weight:600}.tab.active{background:#1b4d8f;color:#fff}
</style>
<div class="fm-header"><h1><i class="fas fa-file-contract me-2"></i> <?php echo e(t('hr.contracts_title')); ?></h1><p><?php echo e(t('hr.contracts_intro')); ?></p></div>
<?php if($message): ?><div class="alert alert-<?php echo $msg_type==='error'?'danger':'success'; ?> alert-dismissible fade show" style="border-radius:8px;"><?php echo e($message); ?><button type="button" class="btn-close" data-bs-dismiss="alert"></button></div><?php endif; ?>
<div class="tabs"><a href="?status=all" class="tab <?php echo $filter==='all'?'active':''; ?>"><?php echo e(t('hr.all')); ?></a><a href="?status=active" class="tab <?php echo $filter==='active'?'active':''; ?>"><?php echo e(t('hr.active_contracts')); ?></a><a href="?status=expired" class="tab <?php echo $filter==='expired'?'active':''; ?>"><?php echo e(t('hr.expired_contracts')); ?></a><a href="?status=terminated" class="tab <?php echo $filter==='terminated'?'active':''; ?>"><?php echo e(t('hr.terminated_contracts')); ?></a></div>
<div class="fm-card"><div class="fm-card-head"><span>📋 <?php echo e(t('hr.contract_records')); ?></span><span class="badge-fm badge-green"><?php echo e(t('hr.contract_count',['count'=>count($contracts)])); ?></span></div><div class="fm-card-body"><div class="table-responsive"><table class="fm-table"><thead><tr><th><?php echo e(t('hr.employee')); ?></th><th><?php echo e(t('hr.contract_type')); ?></th><th><?php echo e(t('hr.start_date')); ?></th><th><?php echo e(t('hr.end_date')); ?></th><th><?php echo e(t('hr.days_remaining')); ?></th><th><?php echo e(t('common.status')); ?></th><th class="text-end"><?php echo e(t('common.actions')); ?></th></tr></thead><tbody>
<?php if(empty($contracts)): ?><tr><td colspan="7" class="text-center py-4 text-muted"><?php echo e(t('hr.no_contracts')); ?></td></tr><?php else: foreach($contracts as $c): $days_left=$c['end_date']?(new DateTime($c['end_date']))->diff(new DateTime())->days:null; $is_expiring=$days_left!==null&&$days_left<=30&&$c['status']==='active'; ?>
<tr style="<?php echo $is_expiring?'background-color:#fff3cd;':''; ?>"><td><strong><?php echo htmlspecialchars($c['emp_name']); ?></strong></td><td><?php echo htmlspecialchars($c['contract_type']); ?></td><td><?php echo $c['start_date']; ?></td><td><?php echo $c['end_date']?:e(t('hr.open_ended')); ?></td><td><?php if($days_left!==null): ?><span class="badge-fm <?php echo $is_expiring?'badge-amber':'badge-green'; ?>"><?php echo $c['status']==='active'?e(t('hr.day_count',['count'=>$days_left])):'-'; ?></span><?php else: ?>-<?php endif; ?></td><td><?php $sm=['active'=>['badge-green','common.active'],'expired'=>['badge-amber','hr.expired_contracts'],'terminated'=>['badge-red','hr.terminated_contracts']]; $cls=$sm[$c['status']][0]??'badge-gray'; $key=$sm[$c['status']][1]??null; ?><span class="badge-fm <?php echo $cls; ?>"><?php echo $key?e(t($key)):e($c['status']); ?></span></td><td class="text-end"><?php if($c['status']==='active'): ?><form method="POST" style="display:inline"><input type="hidden" name="action" value="update_status"><input type="hidden" name="contract_id" value="<?php echo $c['id']; ?>"><input type="hidden" name="status" value="terminated"><button class="btn-fm btn-danger" onclick="return confirm('<?php echo e(t('hr.confirm_cancel_contract')); ?>');"><?php echo e(t('hr.cancel_contract')); ?></button></form><?php endif; ?></td></tr>
<?php endforeach; endif; ?></tbody></table></div></div></div>
<div class="row"><div class="col-md-6"><div class="fm-card"><div class="fm-card-head"><span>➕ <?php echo e(t('hr.add_renew_contract')); ?></span></div><div class="fm-card-body"><form method="POST"><input type="hidden" name="action" value="add"><div class="mb-3"><label class="form-label"><?php echo e(t('hr.employee')); ?></label><select name="employee_id" class="form-select" required><option value=""><?php echo e(t('hr.select_employee')); ?></option><?php foreach($employees as $emp): ?><option value="<?php echo $emp['id']; ?>"><?php echo htmlspecialchars($emp['full_name']); ?></option><?php endforeach; ?></select></div><div class="mb-3"><label class="form-label"><?php echo e(t('hr.contract_type')); ?></label><select name="contract_type" class="form-select" required><option value="دائم"><?php echo e(t('hr.permanent')); ?></option><option value="مؤقت"><?php echo e(t('hr.temporary')); ?></option><option value="عقد مشروع"><?php echo e(t('hr.project_contract')); ?></option><option value="تدريب"><?php echo e(t('hr.training')); ?></option></select></div><div class="mb-3"><label class="form-label"><?php echo e(t('hr.start_date')); ?></label><input type="date" name="start_date" class="form-control" required value="<?php echo date('Y-m-d'); ?>"></div><div class="mb-3"><label class="form-label"><?php echo e(t('hr.end_date')); ?></label><input type="date" name="end_date" class="form-control"></div><div class="mb-3"><label class="form-label"><?php echo e(t('hr.contract_salary')); ?></label><input type="number" step="0.01" name="salary" class="form-control" required></div><div class="mb-3"><label class="form-label"><?php echo e(t('hr.terms_notes')); ?></label><textarea name="terms" class="form-control" rows="3"></textarea></div><button type="submit" class="btn-fm btn-navy" style="width:100%;"><?php echo e(t('hr.save_contract')); ?></button></form></div></div></div></div>
<?php require_once __DIR__ . '/../../includes/footer.php'; ?>
